Repository openshift/lvm-operator, pull requests merged in 2022-11, with the labels that each got.

#284 fix: add missing ns labels for make deploy
  config/manager/manager.yaml
Labels: lgtm, approved

#285 fix: add dissconected env annotation to the CSV
  bundle/manifests/lvm-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
Labels: lgtm, approved

#286 Bug 2139776:[release-4.12] fix: add dissconected env annotation to the CSV
  bundle/manifests/lvm-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
Labels: lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified, approved

#288 fix: github action for lvmo manual build
  .github/workflows/manual-build.yaml
Labels: approved

#290 chore: update the weekly build github action
  .github/workflows/manual-build.yaml
  .github/workflows/weekly-build.yaml
Labels: lgtm, approved

#291 fix: remove debug logging from the manager auth proxy patch
  bundle/manifests/lvm-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, approved

#295 doc: add an upgrade doc
  doc/user-guide/upgrade.md
Labels: lgtm, approved
