Repository openshift/lvm-operator, pull requests merged in 2022-06, with the labels that each got.

#201 fix: creates the thinpool with the -Z option
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved

#204 Bug 2090314: Update CSV annotation
  bundle/manifests/lvm-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/samples/lvm_v1alpha1_lvmcluster.yaml
Labels: lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified, approved

#211 Bug 2056104:[release-4.11] build: update prometheus/client_golang
  go.mod
  go.sum
Labels: lgtm, bugzilla/valid-bug, approved, bugzilla/severity-medium

#205 send vg alerts only when thin pool alerts are also triggered
  bundle/manifests/prometheus-lvmo-rules_monitoring.coreos.com_v1_prometheusrule.yaml
  config/prometheus/prometheus_rules.yaml
  monitoring/alerts/vgalerts.libsonnet
Labels: lgtm, approved

#213 Update default size percent to 90
  api/v1alpha1/lvmcluster_types.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
Labels: lgtm, approved

#210 fix: mark the topolvm storageclass as default
  controllers/topolvm_storageclass.go
Labels: lgtm, approved

#216 Bug 2086557: send vg alerts only when thin pool alerts are also triggered
  bundle/manifests/prometheus-lvmo-rules_monitoring.coreos.com_v1_prometheusrule.yaml
  config/prometheus/prometheus_rules.yaml
  monitoring/alerts/vgalerts.libsonnet
Labels: lgtm, bugzilla/valid-bug, approved, bugzilla/severity-high

#217 Adds the recommended k8s labels to lvmo pods
  bundle/manifests/lvm-node-metrics_v1_service.yaml
  bundle/manifests/lvm-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/lvm-operator.clusterserviceversion.yaml
  bundle/manifests/topolvm-node-metrics_v1_service.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/lvm_metric_service_config.yaml
  config/rbac/topolvm_metric_service_config.yaml
  controllers/defaults.go
  controllers/topolvm_controller.go
  controllers/topolvm_node.go
  controllers/vgmanager_daemonset.go
Labels: lgtm, approved

#202 test: script for testing operator performance
  test/performance/operf.go
Labels: lgtm, approved

#212 fix: update resource request and limits across containers
  bundle/manifests/lvm-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/defaults.go
  controllers/topolvm_controller.go
  controllers/topolvm_node.go
  controllers/vgmanager_daemonset.go
Labels: lgtm, approved
