Repository openshift/lvm-operator, pull requests merged in 2022-12, with the labels that each got.

#296 allow installation of the operator in any namespace
  Makefile
  bundle/manifests/lvm-operator.clusterserviceversion.yaml
  bundle/manifests/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/topolvm-controller_v1_serviceaccount.yaml
  bundle/manifests/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/topolvm-leader-election_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/topolvm-leader-election_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/topolvm-node_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/topolvm-node_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/topolvm-node_v1_serviceaccount.yaml
  bundle/manifests/vg-manager-clusterrole_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/vg-manager-clusterrolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/vg-manager-role_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/vg-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/vg-manager_v1_serviceaccount.yaml
Labels: lgtm, approved

#297 OCPVE-187: Add Chad, Jeremy, and Suleyman to the OWNERS
  OWNERS
Labels: approved, needs-ok-to-test

#300 Replace lvm-operator with lvms wherever required
  Makefile
  bundle.Dockerfile
  bundle/manifests/lvms-metrics_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/lvms-metrics_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/lvms-node-metrics_v1_service.yaml
  bundle/manifests/lvms-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/lvms-operator-metrics-service_v1_service.yaml
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  bundle/manifests/lvms-webhook-service_v1_service.yaml
  bundle/manifests/topolvm-node-metrics_v1_service.yaml
  bundle/metadata/annotations.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_custom_env.yaml.in
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/lvms_metric_service_config.yaml
  config/rbac/lvms_node_role_n_rolebindings.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/rbac/topolvm_metric_service_config.yaml
  config/samples/lvm_v1alpha1_lvmcluster.yaml
  config/webhook/kustomization.yaml
  config/webhook/service.yaml
  controllers/constants.go
  controllers/defaults.go
  controllers/lvmcluster_controller_test.go
  controllers/scc.go
  controllers/topolvm_controller.go
  controllers/topolvm_node.go
  controllers/topolvm_snapshotclass.go
  controllers/topolvm_storageclass.go
  controllers/utils.go
  doc/dev-guide/lvmo-units.md
  doc/usage/install.md
  doc/user-guide/usage.md
  e2e/aws_disk.go
  e2e/config.go
  e2e/lvmcluster.go
  e2e/subscription.go
  e2e/testdata/pvc_tests/volume-snapshot.yaml
  e2e/validation.go
  olm-deploy/kustomization.yaml
  olm-deploy/lvms-catalogsource-image.yaml
  olm-deploy/lvms-catalogsource.yaml
  olm-deploy/lvms-operator-subscription.yaml
  test/performance/operf.go
Labels: lgtm, approved

#301 fix: corrects the image in the CSV
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
Labels: approved

#302 Bug 2153255: Rename lvm-operator to lvms
  Makefile
  bundle.Dockerfile
  bundle/manifests/lvms-metrics_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/lvms-metrics_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/lvms-node-metrics_v1_service.yaml
  bundle/manifests/lvms-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/lvms-operator-metrics-service_v1_service.yaml
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  bundle/manifests/lvms-webhook-service_v1_service.yaml
  bundle/manifests/topolvm-node-metrics_v1_service.yaml
  bundle/metadata/annotations.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_custom_env.yaml.in
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/lvms_metric_service_config.yaml
  config/rbac/lvms_node_role_n_rolebindings.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/rbac/topolvm_metric_service_config.yaml
  config/samples/lvm_v1alpha1_lvmcluster.yaml
  config/webhook/kustomization.yaml
  config/webhook/service.yaml
  controllers/constants.go
  controllers/defaults.go
  controllers/lvmcluster_controller_test.go
  controllers/scc.go
  controllers/topolvm_controller.go
  controllers/topolvm_node.go
  controllers/topolvm_snapshotclass.go
  controllers/topolvm_storageclass.go
  controllers/utils.go
  doc/dev-guide/lvmo-units.md
  doc/usage/install.md
  doc/user-guide/usage.md
  e2e/aws_disk.go
  e2e/config.go
  e2e/lvmcluster.go
  e2e/subscription.go
  e2e/testdata/pvc_tests/volume-snapshot.yaml
  e2e/validation.go
  olm-deploy/kustomization.yaml
  olm-deploy/lvms-catalogsource-image.yaml
  olm-deploy/lvms-catalogsource.yaml
  olm-deploy/lvms-operator-subscription.yaml
  olm-deploy/openshift-storage-namespace.yaml
  test/performance/operf.go
Labels: lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified, approved
