Repository openshift/lvm-operator, pull requests merged in 2022-05, with the labels that each got.

#185 build: update labels in the bundle
  bundle/manifests/controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/lvm-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/lvm-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#162 test: to check the status of pvc as bound and pod as running
  e2e/config.go
  e2e/lvm/lvm_suite_test.go
  e2e/lvm/pvc_test.go
  e2e/testdata.go
  e2e/validation.go
  pkg/deploymanager/LVMCluster.go
Labels: lgtm, approved

#183 feat: volume snapshot class
  bundle/manifests/lvm-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/lvmcluster_controller.go
  controllers/suite_test.go
  controllers/topolvm_snapshotclass.go
  controllers/vgmanager_test.go
  e2e/testdata/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  e2e/validation.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved

#189 Bug 2083441: Volume snapshot class bp
  bundle/manifests/lvm-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/lvmcluster_controller.go
  controllers/suite_test.go
  controllers/topolvm_snapshotclass.go
  controllers/vgmanager_test.go
  e2e/testdata/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  e2e/validation.go
  go.mod
  go.sum
  main.go
Labels: lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified, approved

#190 fix: added volume snapshot api to e2e client scheme
  pkg/deploymanager/config.go
Labels: lgtm, approved

#194 Bug 2083129: update csv correctly
  config/manifests/bases/clusterserviceversion.yaml.in
  config/samples/kustomization.yaml
Labels: lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#177 e2e test: unified the clients
  pkg/deploymanager/common.go
  pkg/deploymanager/config.go
  pkg/deploymanager/subscription.go
Labels: lgtm, approved

#197 fix: specify the go version to be used
  .github/workflows/golangci-lint.yaml
Labels: lgtm

#196 fix: specify the go version to be used
  .github/workflows/golangci-lint.yaml
Labels: lgtm, approved

#188 e2etest: adding and cleaning aws disk
  Makefile
  e2e/aws_disk.go
  e2e/config.go
  e2e/disk_setup.go
  e2e/setup_teardown.go
  e2e/validation.go
  go.mod
  go.sum
Labels: lgtm, approved

#198 chore: github action to build the operator every week
  .github/workflows/weekly-build.yaml
Labels: lgtm, do-not-merge/hold, approved

#200 fix: fixes weekly-build github action
  .github/workflows/weekly-build.yaml
Labels: lgtm, approved
