Repository openshift/lvm-operator, pull requests merged in 2022-03, with the labels that each got.

#113 fix: skip in-use loop devices during vgcreate/vgextend
  pkg/internal/block_device.go
  pkg/internal/exec.go
  pkg/vgmanager/filter.go
Labels: lgtm, approved

#119 fix: adds more approvers and reviewers
  OWNERS
Labels: lgtm, approved

#103 Adding an alert mechanism into lvm-operator
  Makefile
  config/prometheus/kustomization.yaml
  config/prometheus/prometheus_rules.yaml
  monitoring/alerts/alerts.jsonnet
  monitoring/alerts/vgalerts.libsonnet
  monitoring/config.libsonnet
  monitoring/jsonnetfile.json
  monitoring/mixin.libsonnet
Labels: lgtm, approved

#124 build: update the icon in the CSV
  config/manifests/bases/clusterserviceversion.yaml.in
Labels: lgtm, approved

#126 makefile: allow podman usage via makefile
  Makefile
Labels: lgtm, approved

#128 build: add nameprefix to the controller manager
  Makefile
Labels: lgtm, approved

#129 build: update go 1.16 to 1.17
  .github/workflows/docker-build.yaml
  Dockerfile
  Dockerfile.combined
  Dockerfile.vgmanager
  go.mod
Labels: lgtm, approved

#134 fix: remove jmolmo from the OWNERS file
  OWNERS
Labels: approved

#133 fix: implements the nodeSelector check
  config/rbac/vg_manager_role.yaml
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved

#136 build: update golang k8s API's to v0.23
  .github/workflows/codespell.yaml
  controllers/topolvm_controller.go
  controllers/topolvm_node.go
  go.mod
  go.sum
Labels: lgtm

#135 fix: refactors vgmanager-controller code
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved

#138 must-gather: add Makefile target to build must-gather image
  Makefile
  must-gather/README.md
Labels: lgtm, approved

#130 End to end test: Added test suite functions
  Makefile
  e2e/common.go
  e2e/config.go
  e2e/lvm/lvm_suite_test.go
  e2e/setup_teardown.go
  go.mod
  go.sum
  pkg/deploymanager/LVMCluster.go
  pkg/deploymanager/common.go
  pkg/deploymanager/config.go
  pkg/deploymanager/subscription.go
Labels: lgtm, approved
