Repository openshift/lvm-operator, pull requests merged in 2023-06, with the labels that each got.

#355 OCPVE-342: Change copyright in headers
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  api/v1alpha1/lvmvolumegroup_types.go
  api/v1alpha1/lvmvolumegroupnodestatus_types.go
  api/v1alpha1/webhook_suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/metricsexporter/exporter.go
  controllers/constants.go
  controllers/defaults.go
  controllers/lvm_volumegroup.go
  controllers/lvmcluster_controller.go
  controllers/lvmcluster_controller_integration_test.go
  controllers/lvmcluster_controller_watches.go
  controllers/scc.go
  controllers/suite_test.go
  controllers/topolvm_controller.go
  controllers/topolvm_csi_driver.go
  controllers/topolvm_node.go
  controllers/topolvm_snapshotclass.go
  controllers/topolvm_storageclass.go
  controllers/utils.go
  controllers/vgmanager.go
  controllers/vgmanager_daemonset.go
  controllers/vgmanager_test.go
  hack/boilerplate.go.txt
  main.go
  olm-deploy/lvms-catalogsource.yaml
  pkg/internal/block_device.go
  pkg/internal/exec.go
  pkg/internal/test/mock_exec.go
  pkg/vgmanager/device_age.go
  pkg/vgmanager/filter.go
  pkg/vgmanager/lvm.go
  pkg/vgmanager/lvm_test.go
  test/e2e/aws_disk.go
  test/e2e/config.go
  test/e2e/disk_setup.go
  test/e2e/ephemeral_check.go
  test/e2e/helper.go
  test/e2e/lvm_suite_test.go
  test/e2e/lvmcluster.go
  test/e2e/pvc_check.go
  test/e2e/setup_teardown.go
  test/e2e/subscription.go
  test/e2e/utils.go
  test/e2e/validation.go
Labels: lgtm, approved, jira/valid-reference, size/M

#356 OCPVE-349: Add PV and PVC controllers to publish events
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/constants.go
  controllers/lvmcluster_controller.go
  controllers/persistent-volume-claim/controller.go
  controllers/persistent-volume/controller.go
  controllers/utils.go
  docs/design/lvm-operator-manager.md
  main.go
  pkg/internal/block_device.go
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved, jira/valid-reference, size/L

#358 OCPVE-336: Remove must-gather owners file
  must-gather/OWNERS
Labels: lgtm, approved, jira/valid-reference, size/XS

#357 OCPVE-302: feat: fstype e2e tests
  test/e2e/config.go
  test/e2e/ephemeral_check.go
  test/e2e/lvm_suite_test.go
  test/e2e/lvmcluster.go
  test/e2e/pvc_check.go
  test/e2e/setup_teardown.go
Labels: lgtm, approved, jira/valid-reference, size/L

#361 OCPVE-380: feat: rhel 9 and accompanying changes
  Dockerfile
  pkg/internal/block_device.go
  pkg/vgmanager/devices_test.go
  pkg/vgmanager/filter.go
  pkg/vgmanager/filter_test.go
Labels: lgtm, approved, jira/valid-reference, size/M
