Repository openshift/lvm-operator, pull requests merged in 2023-11, with the labels that each got.

#474 OCPVE-766: feat: use embed-lvmd instead of container
  docs/design/architecture.md
  docs/design/lvm-operator-manager.md
  internal/controllers/constants/constants.go
  internal/controllers/lvmcluster/logpassthrough/options.go
  internal/controllers/lvmcluster/logpassthrough/options_test.go
  internal/controllers/lvmcluster/resource/topolvm_node.go
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#476 OCPBUGS-11486: fix: immediately drop leader election in case of shutdown to quicken restart
  cmd/operator/operator.go
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/severity-moderate, jira/valid-bug

#478 OCPBUGS-11486: fix: use native leader lock implementation
  cmd/operator/operator.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-moderate, jira/valid-bug, size/S

#477 OCPBUGS-18708: docs: add validation limitation
  README.md
Labels: lgtm, approved, jira/valid-reference, jira/valid-bug, size/S

#479 OCPBUGS-13558: fix: refactor node removal controller
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  cmd/operator/operator.go
  config/rbac/role.yaml
  internal/controllers/lvmcluster/controller_integration_test.go
  internal/controllers/lvmcluster/suite_test.go
  internal/controllers/node/removal/controller.go
  internal/controllers/node/removal/controller_test.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/valid-bug

#481 OCPBUGS-19324: fix: CVE-2023-37788
  cmd/main.go
  cmd/operator/operator.go
  go.mod
  go.sum
  internal/controllers/lvmcluster/controller_watches.go
  internal/controllers/lvmcluster/resource/topolvm_snapshotclass.go
  internal/controllers/lvmcluster/suite_test.go
  internal/controllers/lvmcluster/vgmanager_resource_test.go
  internal/controllers/vgmanager/controller_test.go
  test/e2e/config_test.go
  test/e2e/lvm_pvc_test.go
  test/e2e/validation_test.go
  test/performance/main.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, size/L, jira/valid-bug

#480 OCPVE-760: Save lvmd config to a configmap instead of a file
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  cmd/vgmanager/vgmanager.go
  config/rbac/vg_manager_role.yaml
  internal/controllers/constants/constants.go
  internal/controllers/lvmcluster/resource/topolvm_node.go
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvmd/lvmd.go
  internal/controllers/vgmanager/lvmd/mocks/mock_configurator.go
Labels: lgtm, approved, jira/valid-reference, size/L

#486 chore: more heap optimizations to get vgmanager < 30 mi of RAM
  cmd/vgmanager/vgmanager.go
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/devices.go
  internal/controllers/vgmanager/lsblk/lsblk.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvm/lvm_test.go
  internal/controllers/vgmanager/lvmd/lvmd.go
Labels: approved, size/M

#487 feat: merge topolvm-controller into lvm-operator
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  bundle/manifests/topolvm-node-metrics_v1_service.yaml
  cmd/operator/operator.go
  config/manager/kustomization.yaml
  config/manager/manager.env
  config/manager/manager.yaml
  config/rbac/topolvm_controller_role_bindings.yaml
  internal/controllers/lvmcluster/controller.go
Labels: approved, size/L

#493 chore: fix broken csi provisioner lib and thus leader election shutdown
  cmd/operator/operator.go
  go.mod
  go.sum
  internal/csi/grpc_runner.go
  internal/csi/provisioner.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v9/controller/controller.go
Labels: approved, size/L

#494 feat: merge csi-resizer into lvm-operator
  Makefile
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  cmd/operator/operator.go
  config/default/manager_custom_env.yaml
  config/default/manager_custom_env.yaml.in
  config/manager/kustomization.yaml
  config/manager/manager.env
  config/manager/manager.yaml
  go.mod
  go.sum
  internal/csi/registrar.go
  internal/csi/resizer.go
  vendor/github.com/kubernetes-csi/external-resizer/LICENSE
  vendor/github.com/kubernetes-csi/external-resizer/pkg/controller/controller.go
  vendor/github.com/kubernetes-csi/external-resizer/pkg/controller/expand_and_recover.go
  vendor/github.com/kubernetes-csi/external-resizer/pkg/controller/inuse_pvc_store.go
  vendor/github.com/kubernetes-csi/external-resizer/pkg/controller/resize_status.go
  vendor/github.com/kubernetes-csi/external-resizer/pkg/csi/client.go
  vendor/github.com/kubernetes-csi/external-resizer/pkg/csi/mock_client.go
  vendor/github.com/kubernetes-csi/external-resizer/pkg/features/features.go
  vendor/github.com/kubernetes-csi/external-resizer/pkg/resizer/csi_resizer.go
  vendor/github.com/kubernetes-csi/external-resizer/pkg/resizer/resizer.go
  vendor/github.com/kubernetes-csi/external-resizer/pkg/resizer/trivial_resizer.go
  vendor/github.com/kubernetes-csi/external-resizer/pkg/util/events.go
  vendor/github.com/kubernetes-csi/external-resizer/pkg/util/util.go
  vendor/modules.txt
Labels: approved, size/XXL

#495 feat: merge csi-snapshotter into lvm-operator
  cmd/operator/operator.go
  go.mod
  go.sum
  internal/csi/provisioner.go
  internal/csi/snapshotter.go
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/factory.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/generic.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/volumegroupsnapshot/interface.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/volumegroupsnapshot/v1alpha1/interface.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/volumegroupsnapshot/v1alpha1/volumegroupsnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/volumegroupsnapshot/v1alpha1/volumegroupsnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/volumegroupsnapshot/v1alpha1/volumegroupsnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/volumesnapshot/interface.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/volumesnapshot/v1/interface.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/volumesnapshot/v1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/volumesnapshot/v1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/volumesnapshot/v1/volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/listers/volumegroupsnapshot/v1alpha1/expansion_generated.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/listers/volumegroupsnapshot/v1alpha1/volumegroupsnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/listers/volumegroupsnapshot/v1alpha1/volumegroupsnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/listers/volumegroupsnapshot/v1alpha1/volumegroupsnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/listers/volumesnapshot/v1/expansion_generated.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/listers/volumesnapshot/v1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/listers/volumesnapshot/v1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/listers/volumesnapshot/v1/volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v6/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/v6/pkg/group_snapshotter/group_snapshotter.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v6/pkg/sidecar-controller/csi_handler.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v6/pkg/sidecar-controller/groupsnapshot_helper.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v6/pkg/sidecar-controller/snapshot_controller.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v6/pkg/sidecar-controller/snapshot_controller_base.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v6/pkg/snapshotter/snapshotter.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v6/pkg/utils/patch.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v6/pkg/utils/util.go
  vendor/modules.txt
Labels: approved, size/XXL

#499 chore: various caching and performance adjustments
  cmd/operator/operator.go
  cmd/vgmanager/vgmanager.go
  config/manager/manager.yaml
  internal/controllers/constants/constants.go
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/dmsetup/dmsetup.go
  internal/controllers/vgmanager/dmsetup/dmsetup_test.go
  internal/controllers/vgmanager/exec/exec.go
  internal/controllers/vgmanager/exec/test/mock_exec.go
  internal/controllers/vgmanager/lsblk/lsblk.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvm/lvm_test.go
  internal/controllers/vgmanager/lvmd/lvmd.go
  internal/controllers/vgmanager/validatelvs_test.go
  internal/controllers/vgmanager/wipefs/wipefs.go
  internal/controllers/vgmanager/wipefs/wipefs_test.go
Labels: approved, size/L

#498 chore: eliminate vg list call to improve performance
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/status.go
Labels: approved, size/L

#500 feat: no periodic reconcile with device selector
  internal/controllers/vgmanager/controller.go
Labels: approved, size/S

#506 fix: csv outdated
  Dockerfile
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
Labels: size/S

#508 fix: trigger update after cm changes
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/lvmd/lvmd.go
Labels: lgtm, approved, size/S

#509 OCPBUGS-23191: Take tolerations into consideration for readiness check
  internal/controllers/lvmcluster/controller.go
Labels: lgtm, approved, jira/valid-reference, jira/valid-bug, size/S

#510 fix: set topology feature flag
  internal/csi/provisioner.go
Labels: size/S

#511 fix: restart and reload lvmd config
  cmd/vgmanager/vgmanager.go
  go.mod
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/lvmd/lvmd.go
Labels: approved, size/L

#512 OCPBUGS-23409: fix: reconcile annotations
  internal/controllers/lvmcluster/resource/topolvm_controller.go
  internal/controllers/lvmcluster/resource/topolvm_node.go
  internal/controllers/lvmcluster/resource/vgmanager.go
Labels: lgtm, approved, jira/valid-reference, jira/valid-bug, size/S

#516 OCPBUGS-23995: fix: set failed status on device check failure
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-low, jira/valid-bug, size/S

#517 OCPBUGS-23375: Add priority class name to lvms resources
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  internal/controllers/constants/constants.go
  internal/controllers/lvmcluster/resource/topolvm_controller.go
  internal/controllers/lvmcluster/resource/topolvm_node.go
  internal/controllers/lvmcluster/resource/vgmanager.go
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
Labels: lgtm, approved, jira/valid-reference, jira/valid-bug, size/S
