Repository openshift/lvm-operator, pull requests merged in 2023-08, with the labels that each got.

#373 OCPVE-606: fix: reenable falsly disabled integration tests
  api/v1alpha1/webhook_suite_test.go
  controllers/suite_test.go
Labels: lgtm, approved, jira/valid-reference, size/XS

#374 chore: adding everyone back to reviewers so we get assigned
  OWNERS
Labels: lgtm

#376 OCPBUGS-11486: fix: correctly determine master nodes by label for SNO
  main.go
  pkg/cluster/leaderelection.go
  pkg/cluster/leaderelection_test.go
Labels: approved, jira/valid-reference, size/L, jira/severity-moderate, jira/valid-bug

#377 OCPBUGS-11486: fix: passthrough unified LE settings to all controllers
  controllers/lvmcluster_controller.go
  controllers/topolvm_controller.go
  main.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/invalid-bug

#380 OCPVE-622: chore: remove deviceMinAge due to imperfect validation
  pkg/vgmanager/device_age.go
  pkg/vgmanager/device_age_test.go
  pkg/vgmanager/devices.go
  pkg/vgmanager/devices_test.go
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved, jira/valid-reference, size/L

#372 OCPBUGS-13558: fix: ensure LVMVolumeGroupNodeStatus is removed by dedicated cleanup controller in case of multi-node
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/lvmcluster_controller_integration_test.go
  controllers/lvmcluster_controller_watches.go
  controllers/node/removal_controller.go
  controllers/suite_test.go
  main.go
  pkg/cluster/leaderelection.go
  pkg/cluster/leaderelection_test.go
  pkg/cluster/sno.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/invalid-bug

#378 OCPVE-619: Refactor E2E Tests to be context aware
  CONTRIBUTING.md
  HACKING.md
  Makefile
  controllers/lvmcluster_controller.go
  controllers/topolvm_snapshotclass.go
  go.mod
  test/e2e/config.go
  test/e2e/ephemeral_check.go
  test/e2e/helper.go
  test/e2e/lvm_suite_test.go
  test/e2e/lvmcluster.go
  test/e2e/pvc_check.go
  test/e2e/setup_teardown.go
  test/e2e/testdata/ephemeral_tests/pod-ephemeral-volume-device.yaml
  test/e2e/testdata/ephemeral_tests/pod-ephemeral-volume-mount.yaml
  test/e2e/testdata/ephemeral_tests/pod-volume-device-template.yaml
  test/e2e/testdata/ephemeral_tests/pod-volume-mount-template.yaml
  test/e2e/testdata/pvc_tests/pod-volume-device-template.yaml
  test/e2e/testdata/pvc_tests/pod-volume-mount-template.yaml
  test/e2e/validation.go
Labels: lgtm, approved, jira/valid-reference, size/XXL

#381 OCPVE-616: fix: add check of correct lv state of thin-pool when vg is already created
  pkg/vgmanager/lv_attr.go
  pkg/vgmanager/lv_attr_test.go
  pkg/vgmanager/lvm.go
  pkg/vgmanager/vgmanager_controller.go
  pkg/vgmanager/vgmanager_controller_test.go
  vendor/github.com/go-logr/logr/testr/testr.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, size/XL

#385 OCPBUGS-17805: Do not error during capacity check if annotation does not exist on the node
  controllers/persistent-volume-claim/controller.go
  controllers/persistent-volume-claim/controller_test.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/invalid-bug

#387 OCPBUGS-17848: fix: don't fail if devices already in vg
  pkg/vgmanager/devices.go
  pkg/vgmanager/devices_test.go
Labels: lgtm, approved, jira/valid-reference, jira/valid-bug, size/S

#386 OCPVE-616: fix: add conditions to error on missing lv in case VG is present but thin-pool is not
  pkg/vgmanager/vgmanager_controller.go
  pkg/vgmanager/vgmanager_controller_test.go
Labels: lgtm, approved, jira/valid-reference, size/M

#389 [release-4.14] OCPBUGS-17857: Do not error during capacity check if annotation does not exist on the node
  controllers/persistent-volume-claim/controller.go
  controllers/persistent-volume-claim/controller_test.go
  controllers/persistent-volume/controller.go
  go.mod
  main.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/valid-bug

#392 OCPVE-361: chore: allow multi-arch with ARCH / OS Flag
  Dockerfile
  Makefile
Labels: lgtm, approved, jira/valid-reference, size/S

#393 OCPVE-588: chore: adjust e2e makefile / remove e2e-test
  Makefile
Labels: lgtm, approved, jira/valid-reference, size/S

#391 OCPVE-627: fix: concurrent apply / status checks -> LVMCluster
  controllers/internal/multierror.go
  controllers/lvm_volumegroup.go
  controllers/lvmcluster_controller.go
  controllers/scc.go
  controllers/topolvm_controller.go
  controllers/topolvm_csi_driver.go
  controllers/topolvm_node.go
  controllers/topolvm_snapshotclass.go
  controllers/topolvm_storageclass.go
  controllers/utils.go
  controllers/vgmanager.go
Labels: lgtm, approved, jira/valid-reference, size/L

#384 OCPVE-620: docs: add guidance on Multi-Node Topology Snapshotting
  README.md
Labels: lgtm, approved, jira/valid-reference, size/S

#398 OCPVE-644: chore: remove redundant err logging and use ctx for passing loggers
  controllers/lvm_volumegroup.go
  controllers/lvmcluster_controller.go
  controllers/lvmcluster_controller_watches.go
  controllers/scc.go
  controllers/suite_test.go
  controllers/topolvm_controller.go
  controllers/topolvm_csi_driver.go
  controllers/topolvm_node.go
  controllers/topolvm_snapshotclass.go
  controllers/topolvm_storageclass.go
  controllers/vgmanager.go
  controllers/vgmanager_test.go
  pkg/vgmanager/devices.go
  pkg/vgmanager/devices_test.go
  pkg/vgmanager/status.go
  pkg/vgmanager/vgmanager_controller.go
  pkg/vgmanager/vgmanager_controller_test.go
Labels: lgtm, approved, jira/valid-reference, size/XL

#396 OCPVE-667: fix: allow no default deviceClass to be set
  api/v1alpha1/lvmcluster_webhook.go
  controllers/topolvm_storageclass.go
  test/e2e/lvmcluster.go
Labels: lgtm, approved, jira/valid-reference, size/L

#402 OCPVE-670: fix ownerref alignment and deletion logic on removal
  controllers/internal/multierror.go
  controllers/lvm_volumegroup.go
  controllers/lvmcluster_controller.go
  controllers/lvmcluster_controller_integration_test.go
  controllers/scc.go
  controllers/topolvm_controller.go
  controllers/topolvm_csi_driver.go
  controllers/topolvm_node.go
  controllers/topolvm_snapshotclass.go
  controllers/topolvm_storageclass.go
  controllers/vgmanager.go
Labels: lgtm, approved, jira/valid-reference, size/L
