Repository openshift/lvm-operator, pull requests merged in 2023-07, with the labels that each got.

#362 OCPVE-404: chore: adding some local helper scripts and makefile updates
  Makefile
  README.md
  hack/git-sanitize.sh
  hack/local-e2e.sh
  hack/release-local.sh
  test/e2e/lvmcluster.go
Labels: lgtm, approved, jira/valid-reference, size/L

#363 OCPVE-404: chore: decoupling the e2e tests from operator deployment
  Makefile
  README.md
  hack/deploy-local.sh
  hack/local-e2e.sh
  hack/release-local.sh
Labels: lgtm, approved, jira/valid-reference, size/M

#360 OCPVE-330: Add add owner reference to created objects
  Makefile
  controllers/lvm_volumegroup.go
  controllers/topolvm_controller.go
  controllers/topolvm_csi_driver.go
  controllers/topolvm_node.go
  test/e2e/setup_teardown.go
Labels: approved, jira/valid-reference, size/M

#365 OCPVE-406: Cluster builds
  HACKING.md
  Makefile
  hack/buildconfig.yaml
  hack/create-buildconfig.sh
Labels: lgtm, approved, jira/valid-reference, size/L

#364 OCPVE-386: feat: added the optionalPaths device selector field
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
  pkg/vgmanager/devices.go
  pkg/vgmanager/devices_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#366 OCPVE-406: fix: updated a few issues with the cluster build commands
  HACKING.md
  Makefile
  hack/create-buildconfig.sh
Labels: lgtm, approved, jira/valid-reference, size/S

#367 chore: add Jakob as lgtm
  OWNERS
Labels: lgtm, approved, size/XS

#369 OCPBUGS-15576: fix: ensure panic safety in PVC controller for non set storageClassName
  controllers/persistent-volume-claim/controller.go
  controllers/persistent-volume-claim/controller_test.go
  controllers/persistent-volume/controller.go
  go.mod
  main.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/valid-bug
