Repository openshift/lvm-operator, pull requests merged in 2023-10, with the labels that each got.

#423 OCPVE-600: Implement the ability to wipe the devices
  .mockery.yaml
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  cmd/vgmanager/vgmanager.go
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
  pkg/dmsetup/dmsetup.go
  pkg/dmsetup/dmsetup_test.go
  pkg/dmsetup/mocks/mock_dmsetup.go
  pkg/internal/exec/exec.go
  pkg/vgmanager/devices.go
  pkg/vgmanager/devices_test.go
  pkg/vgmanager/vgmanager_controller.go
  pkg/vgmanager/wipe_devices.go
  pkg/vgmanager/wipe_devices_test.go
  pkg/wipefs/mocks/mock_wipefs.go
  pkg/wipefs/wipefs.go
  pkg/wipefs/wipefs_test.go
Labels: lgtm, approved, jira/valid-reference, size/XL

#435 OCPVE-600: fix: wiping should not error on optional paths
  pkg/vgmanager/wipe_devices.go
  pkg/vgmanager/wipe_devices_test.go
Labels: lgtm, approved, jira/valid-reference, size/M

#437 OCPVE-220: fix: bring back mistakenly removed webhook patch
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
Labels: lgtm, approved, jira/valid-reference, size/S

#438 OCPVE-709: feat: allow dlv debugging for lvm operator and vgmanager
  CONTRIBUTING.md
  Makefile
  cmd/operator/operator.go
  config/debug/kustomization.yaml
  config/debug/manager_debug_patch.yaml
  hack/debug.Dockerfile
  internal/controllers/lvmcluster/lvmcluster_controller.go
  internal/controllers/lvmcluster/resource/manager.go
  internal/controllers/lvmcluster/resource/vgmanager.go
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
Labels: lgtm, approved, jira/valid-reference, size/L

#439 OCPVE-346: fix: remove build cache mount
  Dockerfile
Labels: lgtm, approved, jira/valid-reference, size/XS

#440 OCPVE-343: feat: allow passthrough for log flags
  cmd/main.go
  cmd/operator/operator.go
  go.mod
  internal/controllers/lvmcluster/logpassthrough/options.go
  internal/controllers/lvmcluster/logpassthrough/options_test.go
  internal/controllers/lvmcluster/lvmcluster_controller.go
  internal/controllers/lvmcluster/resource/manager.go
  internal/controllers/lvmcluster/resource/topolvm_controller.go
  internal/controllers/lvmcluster/resource/topolvm_node.go
  internal/controllers/lvmcluster/resource/vgmanager.go
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
  internal/controllers/lvmcluster/suite_test.go
  internal/controllers/lvmcluster/vgmanager_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#441 OCPVE-347: chore: unify controller naming
  .pre-commit-config.yaml
  cmd/operator/operator.go
  cmd/vgmanager/vgmanager.go
  internal/controllers/lvmcluster/controller.go
  internal/controllers/lvmcluster/controller_integration_test.go
  internal/controllers/lvmcluster/controller_watches.go
  internal/controllers/lvmcluster/suite_test.go
  internal/controllers/lvmcluster/vgmanager_resource_test.go
  internal/controllers/node/removal/controller.go
  internal/controllers/persistent-volume-claim/controller.go
  internal/controllers/persistent-volume-claim/controller_test.go
  internal/controllers/persistent-volume/controller.go
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/devices.go
  internal/controllers/vgmanager/devices_test.go
  internal/controllers/vgmanager/status.go
  internal/controllers/vgmanager/validatelvs_test.go
  internal/controllers/vgmanager/wipe_devices.go
  internal/controllers/vgmanager/wipe_devices_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#443 OCPVE-312: chore: move olm-deploy to config
  Makefile
  config/olm-deploy/kustomization.yaml
  config/olm-deploy/lvms-catalogsource-image.yaml
  config/olm-deploy/lvms-catalogsource.yaml
  config/olm-deploy/lvms-operator-subscription.yaml
  config/olm-deploy/openshift-storage-namespace.yaml
  config/olm-deploy/openshift-storage-operatorgroup.yaml
Labels: lgtm, approved, jira/valid-reference, size/XS

#442 OCPVE-710: chore: bump OPERATOR_SDK_VERSION to 1.32.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
Labels: lgtm, approved, jira/valid-reference, size/S

#444 OCPVE-728: Add Jakob to the approvers list
  OWNERS
Labels: lgtm, approved, jira/valid-reference, size/XS

#447 OCPVE-603: Add lvms tag to volume groups
  cmd/vgmanager/vgmanager.go
  cmd/vgmanager/vgmanager_test.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvm/mocks/mock_lvm.go
Labels: lgtm, approved, jira/valid-reference, size/L

#446 OCPVE-726: Activate inactive logical volumes
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvm/mocks/mock_lvm.go
Labels: lgtm, approved, jira/valid-reference, size/M

#449 Update OWNERS
  OWNERS
Labels: lgtm, approved, size/XS

#448 OCPVE-605: Allow recovering from existing volume groups
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/devices.go
Labels: lgtm, approved, jira/valid-reference, size/M

#432 OCPVE-662: docs: v2 api proposal
  docs/design/proposals/logical-volume-manager-storage-api-v2.md
Labels: lgtm, approved, jira/valid-reference, size/XL

#453 OCPBUGS-22109: fix: restrict namespaced cache to relevant CRDs only
  cmd/operator/operator.go
  internal/controllers/persistent-volume-claim/controller.go
  internal/controllers/persistent-volume-claim/controller_test.go
Labels: lgtm, approved, jira/valid-reference, jira/valid-bug, size/S

#456 OCPBUGS-22109: Sort node names to get consistent event messages
  internal/controllers/persistent-volume-claim/controller.go
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/valid-bug

#458 OCPVE-738: feat: migrate to FBC for catalog in makefile
  Makefile
  catalog.Dockerfile
  catalog/channel.yaml
  catalog/lvms-operator/operator.yaml
  catalog/package.yaml
  hack/verify-catalog.sh
Labels: lgtm, approved, jira/valid-reference, size/L

#460 OCPVE-747: fix: vgmanager thin pool and controller tests and smaller fixes
  .mockery.yaml
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvmd/mocks/mock_configurator.go
Labels: lgtm, approved, jira/valid-reference, size/XL

#461 OCPVE-747: test: various reconcile failure branch tests
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/devices.go
Labels: lgtm, approved, jira/valid-reference, size/L

#462 OCPVE-747: test: increase cluster functions coverage to 100%
  cmd/operator/operator.go
  internal/cluster/leaderelection.go
  internal/cluster/leaderelection_test.go
  internal/cluster/namespace_test.go
  internal/cluster/sno.go
  internal/cluster/sno_test.go
  internal/cluster/type_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#463 OCPBUGS-22362: fix: added the subscription annotation to the bundle csv
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, size/XS, jira/valid-bug

#465 OCPBUGS-22383: fix: added 4.13 subscription annotations
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
Labels: lgtm, jira/valid-reference, jira/severity-important, size/XS, jira/invalid-bug

#466 OCPBUGS-22384: fix: added 4.12 subscription annotations
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, size/XS, jira/invalid-bug

#468 OCPVE-747: test: node removal controller test coverage 100%
  internal/controllers/node/removal/controller.go
  internal/controllers/node/removal/controller_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#469 OCPVE-747: chore: move tagging to avoid coverage on cmd
  cmd/vgmanager/vgmanager.go
  internal/tagging/tagging.go
  internal/tagging/tagging_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#471 OCPVE-722: fix: adding dccache to gitignore and adding project name to snyk comm…
  .gitignore
  Makefile
Labels: lgtm, approved, jira/valid-reference, size/XS
