Repository openshift/lvm-operator, pull requests merged in 2023-09, with the labels that each got.

#403 OCPVE-663: feat: introduce k8s events to lvmcluster and vgmanager
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  cmd/vgmanager/main.go
  config/rbac/vg_manager_role.yaml
  controllers/lvmcluster_controller.go
  controllers/suite_test.go
  controllers/utils.go
  main.go
  pkg/vgmanager/status.go
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved, jira/valid-reference, size/L

#405 OCPBUGS-18354: owns watches config updates
  controllers/lvmcluster_controller.go
  controllers/lvmcluster_controller_watches.go
  controllers/scc.go
  controllers/suite_test.go
  controllers/topolvm_csi_driver.go
  controllers/topolvm_snapshotclass.go
  controllers/topolvm_storageclass.go
  controllers/vgmanager.go
  main.go
  pkg/labels/managed.go
  pkg/vgmanager/status.go
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/invalid-bug

#412 OCPBUGS-18354: chore: remove unnecessary labels from vg manager DaemonSet
  controllers/vgmanager.go
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/valid-bug

#409 OCPVE-677: fix: allow deletion of lvmvolumegroup if lvmd conf was already deleted
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved, jira/valid-reference, size/M

#410 OCPVE-677: chore: separate filter and lvm package from vgmanager
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/lvm/lvm.go
  pkg/lvm/lvm_test.go
  pkg/vgmanager/devices.go
  pkg/vgmanager/devices_test.go
  pkg/vgmanager/status.go
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved, jira/valid-reference, size/L

#414 OCPVE-677: fix: allow deleting all storageclasses / vgs in case one is already gone
  controllers/lvm_volumegroup.go
  controllers/scc.go
  controllers/topolvm_snapshotclass.go
  controllers/topolvm_storageclass.go
Labels: lgtm, approved, jira/valid-reference, size/S

#411 OCPVE-677: chore: separate lvmd package from vgmanager
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroupnodestatuses.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  cmd/vgmanager/main.go
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroupnodestatuses.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  pkg/lvmd/lvmd.go
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved, jira/valid-reference, size/L

#406 OCPVE-677: chore: refactor vgmanager into different interfaces and introduce tests
  .mockery.yaml
  Makefile
  cmd/vgmanager/main.go
  controllers/constants.go
  controllers/topolvm_node.go
  go.mod
  go.sum
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/internal/exec/exec.go
  pkg/lsblk/mocks/mock_lsblk.go
  pkg/lvm/lvm.go
  pkg/lvm/lvm_test.go
  pkg/lvm/mocks/mock_lvm.go
  pkg/vgmanager/devices.go
  pkg/vgmanager/devices_test.go
  pkg/vgmanager/status.go
  pkg/vgmanager/suite_test.go
  pkg/vgmanager/vgmanager_controller.go
  pkg/vgmanager/vgmanager_controller_test.go
  pkg/vgmanager/vgmanager_validatelvs_test.go
  vendor/github.com/stretchr/objx/.codeclimate.yml
  vendor/github.com/stretchr/objx/.gitignore
  vendor/github.com/stretchr/objx/LICENSE
  vendor/github.com/stretchr/objx/README.md
  vendor/github.com/stretchr/objx/Taskfile.yml
  vendor/github.com/stretchr/objx/accessors.go
  vendor/github.com/stretchr/objx/conversions.go
  vendor/github.com/stretchr/objx/doc.go
  vendor/github.com/stretchr/objx/map.go
  vendor/github.com/stretchr/objx/mutations.go
  vendor/github.com/stretchr/objx/security.go
  vendor/github.com/stretchr/objx/tests.go
  vendor/github.com/stretchr/objx/type_specific.go
  vendor/github.com/stretchr/objx/type_specific_codegen.go
  vendor/github.com/stretchr/objx/value.go
  vendor/github.com/stretchr/testify/mock/doc.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, size/XXL

#419 OCPVE-265: chore: add pre-commit config
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yaml
  .github/workflows/conf/yamllint.yaml
  .github/workflows/dependencies.yaml
  .github/workflows/docker-build.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/manual-build.yaml
  .github/workflows/weekly-build.yaml
  .github/workflows/yamllint.yaml
  .mockery.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Dockerfile
  Makefile
  README.md
  cmd/metricsexporter/main.go
  controllers/persistent-volume-claim/controller_test.go
  controllers/suite_test.go
  docs/design/architecture.md
  docs/design/lvm-operator-manager.md
  docs/design/thin-provisioning.md
  docs/troubleshooting.md
  hack/buildconfig.yaml
  hack/create-buildconfig.sh
  hack/deploy-local.sh
  hack/git-sanitize.sh
  hack/publish-codecov.sh
  hack/release-local.sh
  hack/verify-bundle.sh
  hack/verify-deps.sh
  hack/verify-generated.sh
  hack/verify-gofmt.sh
  monitoring/alerts/alerts.jsonnet
  monitoring/mixin.libsonnet
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_clusterscoped_resources
  must-gather/collection-scripts/gather_namespaced_resources
  must-gather/collection-scripts/gather_node_info
  pkg/vgmanager/lv_attr.go
  pkg/vgmanager/status.go
  pkg/vgmanager/suite_test.go
  pkg/vgmanager/vgmanager_controller.go
  test/e2e/helper.go
  test/e2e/subscription.go
  test/e2e/testdata/ephemeral_tests/ephemeral-snapshot-restore.yaml
  test/e2e/testdata/ephemeral_tests/pod-ephemeral-volume-device.yaml
  test/e2e/testdata/ephemeral_tests/pod-volume-device-template.yaml
  test/e2e/testdata/pvc_tests/pod-volume-device-template.yaml
  test/e2e/testdata/pvc_tests/pvc-snapshot-restore-template.yaml
  test/e2e/testdata/pvc_tests/volume-snapshot.yaml
  test/performance/operf.go
Labels: lgtm, approved, jira/valid-reference, size/XL

#420 OCPVE-677: fix: vgmanager unit tests failure on Darwin due to symlinked Temp Dir
  pkg/vgmanager/devices_test.go
  pkg/vgmanager/kname_test.go
  pkg/vgmanager/suite_test.go
  pkg/vgmanager/vgmanager_controller_test.go
Labels: lgtm, approved, jira/valid-reference, size/M

#422 OCPBUGS-18354: fix: remove volumesnapshotclass from default resource deletion list
  controllers/lvmcluster_controller.go
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/valid-bug

#425 OCPVE-352: Remove unused metrics-exporter
  Dockerfile
  bundle/manifests/lvms-node-metrics_v1_service.yaml
  bundle/manifests/lvms-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/lvms-operator-metrics-service_v1_service.yaml
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  cmd/metricsexporter/main.go
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/lvms_metric_service_config.yaml
  docs/design/architecture.md
  go.mod
  test/performance/operf.go
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, size/XL

#424 OCPVE-669: chore: refactor e2e tests
  controllers/lvmcluster_controller.go
  test/e2e/aws_disk_test.go
  test/e2e/config_test.go
  test/e2e/disk_setup_test.go
  test/e2e/ephemeral_check.go
  test/e2e/helper.go
  test/e2e/helper_test.go
  test/e2e/lvm_cluster_test.go
  test/e2e/lvm_pvc_test.go
  test/e2e/lvm_suite_test.go
  test/e2e/lvmcluster.go
  test/e2e/pod_runner_test.go
  test/e2e/pvc_check.go
  test/e2e/setup_teardown.go
  test/e2e/subscription_test.go
  test/e2e/testdata/ephemeral_tests/ephemeral-clone.yaml
  test/e2e/testdata/ephemeral_tests/ephemeral-snapshot-restore.yaml
  test/e2e/testdata/ephemeral_tests/ephemeral-volume-snapshot.yaml
  test/e2e/testdata/ephemeral_tests/pod-ephemeral-volume-device.yaml
  test/e2e/testdata/ephemeral_tests/pod-ephemeral-volume-mount.yaml
  test/e2e/testdata/ephemeral_tests/pod-volume-device-template.yaml
  test/e2e/testdata/ephemeral_tests/pod-volume-mount-template.yaml
  test/e2e/testdata/pvc_tests/pod-volume-device-template.yaml
  test/e2e/testdata/pvc_tests/pod-volume-mount-template.yaml
  test/e2e/testdata/pvc_tests/pvc-clone-template.yaml
  test/e2e/testdata/pvc_tests/pvc-snapshot-restore-template.yaml
  test/e2e/testdata/pvc_tests/pvc-template.yaml
  test/e2e/testdata/pvc_tests/volume-snapshot-template.yaml
  test/e2e/testdata/pvc_tests/volume-snapshot.yaml
  test/e2e/utils.go
  test/e2e/validation_test.go
Labels: lgtm, approved, jira/valid-reference, size/XXL

#428 OCPBUGS-18708: fix: disallow creation of LVMCluster outside of operator namespace and restrict cache
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_webhook.go
  api/v1alpha1/webhook_suite_test.go
  main.go
  pkg/cluster/namespace.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/valid-bug

#429 OCPVE-707: chore: unify build binaries and optimize dockerfile
  Dockerfile
  Makefile
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  cmd/main.go
  cmd/operator/operator.go
  cmd/vgmanager/vgmanager.go
  config/manager/manager.yaml
  controllers/vgmanager_daemonset.go
  go.mod
Labels: lgtm, approved, jira/valid-reference, size/L

#413 OCPVE-220: remove unused certificates
  Dockerfile
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_lvmclusters.yaml
  config/crd/patches/cainjection_in_lvmvolumegroupnodestatuses.yaml
  config/crd/patches/cainjection_in_lvmvolumegroups.yaml
  config/crd/patches/webhook_in_lvmclusters.yaml
  config/crd/patches/webhook_in_lvmvolumegroupnodestatuses.yaml
  config/crd/patches/webhook_in_lvmvolumegroups.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  config/manifests/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  controllers/constants.go
  controllers/topolvm_controller.go
  docs/design/lvm-operator-manager.md
Labels: lgtm, approved, jira/valid-reference, size/L

#426 OCPVE-665: feat: report filter status into vgstatus
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmvolumegroupnodestatus_types.go
  api/v1alpha1/webhook_suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroupnodestatuses.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroupnodestatuses.yaml
  controllers/lvmcluster_controller.go
  go.mod
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/vgmanager/devices.go
  pkg/vgmanager/devices_test.go
  pkg/vgmanager/status.go
  pkg/vgmanager/suite_test.go
  pkg/vgmanager/vgmanager_controller.go
  pkg/vgmanager/vgmanager_controller_test.go
Labels: lgtm, approved, jira/valid-reference, size/XXL

#430 OCPVE-697: test: various webhook test cases
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_webhook.go
Labels: lgtm, approved, jira/valid-reference, size/L

#433 OCPVE-390: use specific cipher suites for kube-rbac-proxy
  bundle/manifests/topolvm-metrics_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/topolvm-metrics_rbac.authorization.k8s.io_v1_rolebinding.yaml
  config/rbac/kustomization.yaml
  config/rbac/topolvm_node_role_n_rolebindings.yaml
  controllers/topolvm_node.go
Labels: lgtm, approved, jira/valid-reference, size/M
