Repository openshift/lvm-operator, pull requests merged in 2023-05, with the labels that each got.

#333 OCPVE-230: Improve README content
  CONTRIBUTING.md
  README.md
  controllers/lvmcluster_controller.go
  doc/dev-guide/index.md
  doc/usage/install.md
  doc/user-guide/upgrade.md
  doc/user-guide/usage.md
  docs/README.md
  docs/design/lvmo-units.md
  docs/design/operator.md
  docs/design/reconciler.md
  docs/design/thin-pool.md
  docs/design/topolvm-csi.md
  docs/design/vg-manager.md
Labels: lgtm, approved, jira/valid-reference, size/XL

#336 OCPVE-286: Introduce code coverage tooling
  .codecov.yml
  Makefile
  controllers/lvmcluster_controller_integration_test.go
  controllers/suite_test.go
  controllers/vgmanager_test.go
  hack/publish-codecov.sh
  pkg/vgmanager/filter_test.go
  test/e2e/aws_disk.go
  test/e2e/common.go
  test/e2e/config.go
  test/e2e/disk_setup.go
  test/e2e/ephemeral_check.go
  test/e2e/helper.go
  test/e2e/lvm_suite_test.go
  test/e2e/lvmcluster.go
  test/e2e/pvc_check.go
  test/e2e/setup_teardown.go
  test/e2e/subscription.go
  test/e2e/testdata/ephemeral_tests/ephemeral-clone.yaml
  test/e2e/testdata/ephemeral_tests/ephemeral-snapshot-restore.yaml
  test/e2e/testdata/ephemeral_tests/ephemeral-volume-snapshot.yaml
  test/e2e/testdata/ephemeral_tests/pod-ephemeral-volume-device.yaml
  test/e2e/testdata/ephemeral_tests/pod-ephemeral-volume-mount.yaml
  test/e2e/testdata/ephemeral_tests/pod-volume-device-template.yaml
  test/e2e/testdata/ephemeral_tests/pod-volume-mount-template.yaml
  test/e2e/testdata/pvc_tests/pod-volume-device-template.yaml
  test/e2e/testdata/pvc_tests/pod-volume-mount-template.yaml
  test/e2e/testdata/pvc_tests/pvc-clone-template.yaml
  test/e2e/testdata/pvc_tests/pvc-snapshot-restore-template.yaml
  test/e2e/testdata/pvc_tests/pvc-template.yaml
  test/e2e/testdata/pvc_tests/volume-snapshot-template.yaml
  test/e2e/testdata/pvc_tests/volume-snapshot.yaml
  test/e2e/testdata/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  test/e2e/utils.go
  test/e2e/validation.go
Labels: lgtm, approved, jira/valid-reference, size/L

#334 OCPVE-231: Improve the design docs
  README.md
  controllers/lvmcluster_controller.go
  docs/README.md
  docs/design/lvm-operator-manager.md
  docs/design/lvmo-units.md
  docs/design/operator.md
  docs/design/reconciler.md
  docs/design/thin-pool.md
  docs/design/thin-provisioning.md
  docs/design/topolvm-csi.md
  docs/design/vg-manager.md
Labels: lgtm, approved, jira/valid-reference, size/XL

#340 OCPBUGS-13364: fix: Added a tag for arm64 to have it pulled into Openshift for ARM
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
Labels: lgtm, bugzilla/valid-bug, approved, jira/valid-reference, size/XS, jira/valid-bug

#341 OCPVE-337: Add an architecture diagram
  README.md
  controllers/lvmcluster_controller.go
  docs/README.md
  docs/design/architecture.md
  docs/design/lvm-operator-manager.md
  docs/design/reconciler.md
  docs/design/vg-manager.md
Labels: lgtm, approved, jira/valid-reference, size/M

#342 [release-4.13] OCPBUGS-13886: fix: Added a tag for arm64 to have it pulled into Openshift for ARM
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
Labels: lgtm, jira/valid-reference, size/XS, jira/invalid-bug

#344 OCPVE-300: OCPVE-301: feat: ext4 support
  api/v1alpha1/lvmcluster_types.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/samples/lvm_v1alpha1_lvmcluster.yaml
  controllers/constants.go
  controllers/topolvm_storageclass.go
  ext4steps.txt
Labels: lgtm, approved, jira/valid-reference, size/M

#347 OCPVE-300: accidentally added my notes
  ext4steps.txt
Labels: lgtm, approved, jira/valid-reference, size/S

#348 OCPVE-362: feat: Marked the operator bundle capabilities level as Seamless Upgrades
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-reference, size/XS

#349 OCPVE-300: fix: added validation around fstype
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
Labels: lgtm, approved, jira/valid-reference, size/M

#354 OCPVE-355: add github issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: lgtm, approved, jira/valid-reference, size/XS

#339 OCPBUGS-10534: Refactor status reporting logic to send updates more often
  api/v1alpha1/lvmvolumegroupnodestatus_types.go
  cmd/vgmanager/main.go
  controllers/lvmcluster_controller.go
  pkg/vgmanager/devices.go
  pkg/vgmanager/devices_test.go
  pkg/vgmanager/status.go
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved, jira/valid-reference, size/XXL, jira/severity-moderate, jira/valid-bug

#352 OCPVE-333: check create or update functions
  controllers/lvm_volumegroup.go
  controllers/topolvm_controller.go
  controllers/topolvm_csi_driver.go
  go.mod
Labels: lgtm, approved, jira/valid-reference, size/L

#343 OCPVE-233: Add a troubleshooting guide
  README.md
  docs/README.md
  docs/design/lvm-operator-manager.md
  docs/troubleshooting.md
Labels: lgtm, approved, jira/valid-reference, size/L
