Repository openshift/lvm-operator, pull requests merged in 2023-04, with the labels that each got.

#314 OCPBUGS-11309: Provide a way to add replaces and skips in the CSV
  Makefile
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manifests/bases/kustomization.yaml
  config/manifests/kustomization.yaml
Labels: jira/valid-reference, jira/invalid-bug

#316 OCPBUGS-11426: Add missing workload management annotations
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, jira/valid-reference, jira/severity-important, jira/valid-bug

#319 OCPBUGS-11047: Add a watcher for storage class objects to the operator
  controllers/lvmcluster_controller_watches.go
  controllers/topolvm_storageclass.go
Labels: lgtm, bugzilla/valid-bug, jira/valid-reference, jira/valid-bug

#320 OCPBUGS-11893: Enable updating initcontainer images during an upgrade
  controllers/topolvm_controller.go
  controllers/topolvm_node.go
Labels: lgtm, bugzilla/valid-bug, jira/valid-reference, jira/valid-bug

#325 Improve readme
  README.md
Labels: lgtm

#326 OCPVE-310: Reduce reconcile interval for delayed devices
  pkg/vgmanager/vgmanager_controller.go
Labels: jira/valid-reference

#327 OCPVE-328: Update dev images to use the new lvms_dev registry
  Makefile
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manager/manager.env
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
  controllers/defaults.go
  doc/usage/install.md
  must-gather/README.md
  olm-deploy/kustomization.yaml
Labels: lgtm, jira/valid-reference

#329 OCPVE-311: Improve Make targets to work on MacOS as well
  Makefile
Labels: lgtm, jira/valid-reference

#330 OCPVE-334: Add verify target to check go formatting and generated files
  Makefile
  config/default/manager_custom_env.yaml
  config/manager/kustomization.yaml
  hack/verify-bundle.sh
  hack/verify-deps.sh
  hack/verify-generated.sh
  hack/verify-gofmt.sh
Labels: lgtm, jira/valid-reference

#331 OCPVE-334: Change VERSION to OPERATOR_VERSION in the Makefile
  Makefile
Labels: lgtm, jira/valid-reference

#332 OCPVE-335: update the OWNERS file
  OWNERS
Labels: lgtm, jira/valid-reference
