Repository openshift/lvm-operator, pull requests merged in 2024-10, with the labels that each got.

#733 [release-4.14] OCPBUGS-42464: Update google.golang.org/protobuf to 1.33.0
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/encoding/json/decode.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, size/XXL, jira/valid-bug

#739 NO-JIRA: Remove jakobmoellerdev from owners
  OWNERS_ALIASES
Labels: lgtm, approved, jira/valid-reference, size/XS

#740 NO-JIRA: fix: add jeremy poulin to our owners files
  OWNERS_ALIASES
Labels: lgtm, approved, jira/valid-reference, size/XS

#728 OCPEDGE-1230: add metadata size field
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvm/lvm_test.go
  internal/controllers/vgmanager/lvm/mocks/mock_lvm.go
  internal/controllers/vgmanager/validatelvs_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#756 OCPBUGS-43523: feat(webhook): fix typo
  api/v1alpha1/lvmcluster_webhook.go
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/severity-moderate, jira/valid-bug

#761 OCPEDGE-825: Konflux branch merge
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
  bundle.konflux.Dockerfile
  must-gather/konflux.Dockerfile
Labels: lgtm, approved, jira/valid-reference, size/XXL

#764 OCPEDGE-824: Adjust bundle to resemble released bundles
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  bundle.konflux.Dockerfile
  hack/render_templates.sh
Labels: lgtm, approved, jira/valid-reference, size/L

#768 NO-JIRA: Adjust triggers for the Konflux pipelines
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
Labels: lgtm, approved, jira/valid-reference, size/S

#769 NO-JIRA: chore: remove Konflux pipelines from main-rhtap
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
Labels: lgtm, approved, jira/valid-reference, size/XXL

#773 NO-JIRA: chore: remove deprecated infrastructure-features annotation
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-reference, size/XS
