Repository openshift/lvm-operator, pull requests merged in 2024-07, with the labels that each got.

#652 OCPEDGE-1126: feat: make lvms microshift aware during vgmanager mounting
  internal/controllers/vgmanager/lvmd/lvmd.go
Labels: lgtm, approved, jira/valid-reference, size/XS

#654 NO-JIRA: Add missing env vars
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
Labels: lgtm, approved, jira/valid-reference, size/S

#655 [release-4.14] OCPBUGS-35917: fix: add missing health probe on lvmd container
  controllers/topolvm_node.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, jira/valid-bug, size/S

#637 OCPBUGS-35918: fix: make lvms report a proper go.mod version
  .mockery.yaml
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_webhook.go
  cmd/main.go
  cmd/operator/operator.go
  cmd/vgmanager/vgmanager.go
  go.mod
  internal/controllers/lvmcluster/controller.go
  internal/controllers/lvmcluster/controller_integration_test.go
  internal/controllers/lvmcluster/controller_watches.go
  internal/controllers/lvmcluster/resource/lvm_volumegroup.go
  internal/controllers/lvmcluster/resource/lvm_volumegroupnodestatus.go
  internal/controllers/lvmcluster/resource/manager.go
  internal/controllers/lvmcluster/resource/scc.go
  internal/controllers/lvmcluster/resource/topolvm_csi_driver.go
  internal/controllers/lvmcluster/resource/topolvm_snapshotclass.go
  internal/controllers/lvmcluster/resource/topolvm_storageclass.go
  internal/controllers/lvmcluster/resource/utils.go
  internal/controllers/lvmcluster/resource/vgmanager.go
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
  internal/controllers/lvmcluster/selector/selector.go
  internal/controllers/lvmcluster/selector/selector_test.go
  internal/controllers/lvmcluster/status.go
  internal/controllers/lvmcluster/status_test.go
  internal/controllers/lvmcluster/suite_test.go
  internal/controllers/lvmcluster/vgmanager_resource_test.go
  internal/controllers/node/removal/controller.go
  internal/controllers/node/removal/controller_test.go
  internal/controllers/persistent-volume-claim/controller.go
  internal/controllers/persistent-volume-claim/controller_test.go
  internal/controllers/persistent-volume/controller.go
  internal/controllers/persistent-volume/controller_test.go
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/devices.go
  internal/controllers/vgmanager/devices_test.go
  internal/controllers/vgmanager/dmsetup/dmsetup.go
  internal/controllers/vgmanager/dmsetup/dmsetup_test.go
  internal/controllers/vgmanager/filter/filter.go
  internal/controllers/vgmanager/filter/filter_test.go
  internal/controllers/vgmanager/lsblk/lsblk.go
  internal/controllers/vgmanager/lsblk/mocks/mock_lsblk.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvm/lvm_test.go
  internal/controllers/vgmanager/lvm/mocks/mock_lvm.go
  internal/controllers/vgmanager/status.go
  internal/controllers/vgmanager/validatelvs_test.go
  internal/controllers/vgmanager/wipe_devices.go
  internal/controllers/vgmanager/wipe_devices_test.go
  internal/controllers/vgmanager/wipefs/wipefs.go
  internal/controllers/vgmanager/wipefs/wipefs_test.go
  internal/migration/microlvms/cleanup.go
  internal/migration/microlvms/cleanup_test.go
  test/e2e/config_test.go
  test/e2e/helper_test.go
  test/e2e/lvm_cluster_test.go
  test/e2e/lvm_pvc_test.go
  test/e2e/validation_test.go
  test/performance/main.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, size/L, jira/valid-bug

#663 [release-4.12] OCPBUGS-33087: chore: add OpenShift Kubernetes Engine to valid subscriptions
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/valid-bug

#665 NO-JIRA: chore: bump google.golang.org/grpc to 1.65.0
  go.mod
  go.sum
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirst.go
  vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand_go1.21.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/resolver/dns/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, size/XL

#669 NO-JIRA: chore: update lvm-operator Konflux jobs
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  bundle.konflux.Dockerfile
Labels: approved, jira/valid-reference, size/L

#658 OCPBUGS-34227: fix: move checks into readiness and introduce grpc health
  cmd/vgmanager/vgmanager.go
  internal/controllers/lvmcluster/controller.go
  internal/controllers/lvmcluster/resource/csi_node.go
  internal/controllers/lvmcluster/suite_test.go
  internal/csi/grpc_runner.go
  internal/csi/health.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/severity-moderate, jira/valid-bug

#673 [release-4.14] OCPBUGS-36368: fixup lvmd socket
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-critical, jira/valid-bug, size/S

#674 OCPEDGE-1160: add lsblk output
  must-gather/collection-scripts/gather_node_info
Labels: lgtm, approved, jira/valid-reference, size/XS

#677 NO-JIRA: chore: remove deprecated BASE_IMAGES_DIGESTS from Konflux jobs
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
Labels: approved, jira/valid-reference, size/S

#679 OCPEDGE-1169: fix: device selection only by filter
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/devices.go
  internal/controllers/vgmanager/devices_test.go
  internal/controllers/vgmanager/filter/filter.go
  internal/controllers/vgmanager/filter/filter_test.go
  internal/controllers/vgmanager/lsblk/lsblk.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvm/lvm_test.go
  internal/controllers/vgmanager/wipe_devices.go
  internal/controllers/vgmanager/wipe_devices_test.go
Labels: lgtm, approved, jira/valid-reference, size/XL

#682 OCPBUGS-37749: fix: terminationMessagePolicy -> FallbackToLogsOnError
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/manager/manager.yaml
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/severity-low, jira/valid-bug
