Repository openshift/lvm-operator, pull requests merged in 2024-04, with the labels that each got.

#595 OCPEDGE-998: fix: avoid restart of vgmanager on config reload
  cmd/vgmanager/vgmanager.go
  go.mod
  go.sum
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvmd/lvmd.go
  vendor/github.com/topolvm/topolvm/internal/runners/metrics_exporter.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, size/L

#601 [release-4.13] OCPBUGS-31625: chore: update feature annotations for lvms
  Makefile
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-reference, size/M, jira/valid-bug

#596 OCPEDGE-1000: feat: implement thick provisioning
  Makefile
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmvolumegroup_types.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
  internal/controllers/lvmcluster/resource/topolvm_snapshotclass.go
  internal/controllers/lvmcluster/resource/vgmanager.go
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvmd/lvmd.go
  test/e2e/helper_test.go
  test/e2e/lvm_cluster_test.go
  test/e2e/lvm_pvc_test.go
  test/e2e/lvm_suite_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#603 OCPBUGS-30266: fix: introduce minimum allocation sizes
  cmd/operator/operator.go
  go.mod
  go.sum
  internal/controllers/constants/constants.go
  vendor/github.com/topolvm/topolvm/Makefile
  vendor/github.com/topolvm/topolvm/internal/controller/node_controller.go
  vendor/github.com/topolvm/topolvm/internal/driver/allocation_settings.go
  vendor/github.com/topolvm/topolvm/internal/driver/controller.go
  vendor/github.com/topolvm/topolvm/internal/driver/node.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/device_class_manager.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/lvservice.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/vgservice.go
  vendor/github.com/topolvm/topolvm/pkg/driver/controller.go
  vendor/github.com/topolvm/topolvm/versions.mk
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, size/L, jira/valid-bug

#604 OCPBUGS-32239: chore: bump golang.org/x/net v0.23.0
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, jira/valid-bug, size/XL

#609 OCPBUGS-32268: chore: remove image based FBC and replace with dynamic generation
  Makefile
  catalog/lvms-operator/operator.yaml
  catalog/lvms-operator/v0.0.1.yaml
  hack/verify-catalog.sh
Labels: lgtm, approved, jira/valid-reference, size/L, jira/severity-low, jira/valid-bug

#610 [release-4.15] OCPBUGS-32269: chore: remove image based FBC and replace with dynamic generation
  Makefile
  catalog/lvms-operator/operator.yaml
  catalog/lvms-operator/v0.0.1.yaml
  hack/verify-catalog.sh
Labels: lgtm, approved, jira/valid-reference, size/L, jira/severity-low, jira/valid-bug

#611 OCPBUGS-32268: fix: depend on opm in catalog make task
  Makefile
  catalog/lvms-operator/v0.0.1.yaml
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/severity-low, jira/valid-bug

#612 OCPBUGS-30830: Accommodate the case in readiness calculation where readyVGCount is greater than expectedVGCount
  internal/controllers/lvmcluster/controller.go
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/severity-low, jira/valid-bug

#615 OCPEDGE-922: Bring more visibility to dynamic device discovery by warnings and a new status field
  README.md
  api/v1alpha1/lvmcluster_webhook.go
  api/v1alpha1/lvmvolumegroupnodestatus_types.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroupnodestatuses.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroupnodestatuses.yaml
  hack/verify-catalog.sh
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/status.go
Labels: lgtm, approved, jira/valid-reference, size/L

#616 OCPEDGE-1005: must-gather: add support for --since and --since-time flags
  must-gather/README.md
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_clusterscoped_resources
  must-gather/collection-scripts/gather_common
  must-gather/collection-scripts/gather_namespaced_resources
Labels: lgtm, approved, jira/valid-reference, size/M

#618 OCPBUGS-33026: Add OpenShift Kubernetes Engine to valid subscriptions
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-reference, jira/valid-bug, size/S
