Repository openshift/lvm-operator, pull requests merged in 2024-06, with the labels that each got.

#576 OCPEDGE-1123: allow user defined device classes
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_webhook.go
  internal/controllers/lvmcluster/controller.go
  internal/controllers/lvmcluster/resource/utils.go
  internal/controllers/lvmcluster/resource/vgmanager.go
  internal/controllers/lvmcluster/selector/selector.go
  internal/controllers/lvmcluster/selector/selector_test.go
  internal/controllers/lvmcluster/status.go
  internal/controllers/lvmcluster/status_test.go
  test/e2e/lvm_cluster_test.go
  test/e2e/lvm_pvc_test.go
  test/e2e/lvm_suite_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#631 OCPBUGS-33304: fix: Rework LVMVolumeGroupNodeStatus management
  internal/controllers/lvmcluster/controller.go
  internal/controllers/lvmcluster/controller_integration_test.go
  internal/controllers/lvmcluster/resource/lvm_volumegroupnodestatus.go
  internal/controllers/lvmcluster/selector/selector.go
  internal/controllers/lvmcluster/suite_test.go
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/severity-moderate, jira/valid-bug

#633 OCPBUGS-34227: feat: chunk size policy
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvm/lvm_test.go
  internal/controllers/vgmanager/lvm/mocks/mock_lvm.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/valid-bug

#635 [release-4.16] OCPBUGS-35404: feat: chunk size policy
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvm/lvm_test.go
  internal/controllers/vgmanager/lvm/mocks/mock_lvm.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/valid-bug

#639 OCPBUGS-35915: [release-4.14] fix: reduce log spam due to filtered devices
  pkg/vgmanager/devices.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, size/XS, jira/valid-bug

#638 OCPEDGE-1126: feat: make lvms microshift aware during vgmanager mounting
  internal/cluster/type.go
  internal/controllers/lvmcluster/controller.go
  internal/controllers/lvmcluster/resource/vgmanager.go
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
  internal/controllers/lvmcluster/vgmanager_resource_test.go
  internal/controllers/vgmanager/lvmd/lvmd.go
Labels: lgtm, approved, jira/valid-reference, size/M

#643 OCPBUGS-34227: fix: actually pass through and validate chunk size
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/validatelvs_test.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#640 OCPBUGS-35916: fix: discover topolvm based SCs that are not part of the generated device classes from LVMCluster
  internal/controllers/persistent-volume-claim/controller.go
  internal/controllers/persistent-volume-claim/controller_test.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#644 [openshift-4.16] OCPBUGS-35404: fix: actually pass through and validate chunk size
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/validatelvs_test.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#642 OCPEDGE-1165: fix: Ensure no racy CSI plugin registration, better startup behavior for vgmanager, failing test summary artifact
  Makefile
  api/v1alpha1/lvmcluster_test.go
  cmd/vgmanager/vgmanager.go
  internal/controllers/lvmcluster/resource/topolvm_csi_driver.go
  internal/controllers/lvmcluster/resource/vgmanager.go
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
  internal/csi/grpc_runner.go
  internal/csi/registrar.go
  test/e2e/config_test.go
  test/e2e/helper_test.go
  test/e2e/lvm_cluster_test.go
  test/e2e/lvm_pvc_test.go
  test/e2e/lvm_suite_test.go
  test/e2e/validation_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#648 OCPEDGE-549: Remove temporary tagging logic
  cmd/vgmanager/vgmanager.go
  internal/migration/tagging/tagging.go
  internal/migration/tagging/tagging_test.go
Labels: lgtm, approved, jira/valid-reference, size/L

#649 OCPBUGS-36155: Disallow changing node selector after initial deployment
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_webhook.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug
