Repository openshift/lvm-operator, pull requests merged in 2024-08, with the labels that each got.

#683 OCPBUGS-37711: fix: use marker annotation to determine successful wipe and rewipe on failure
  internal/controllers/constants/constants.go
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/devices.go
  internal/controllers/vgmanager/wipe_devices.go
  internal/controllers/vgmanager/wipe_devices_test.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/severity-low, jira/valid-bug

#687 OCPBUGS-37711: fix: ensure wipefs / dmsetup remove use CombinedOutput to wait for both STDERR and STDOUT before continuing
  internal/controllers/lvmcluster/resource/csi_node.go
  internal/controllers/vgmanager/dmsetup/dmsetup.go
  internal/controllers/vgmanager/dmsetup/dmsetup_test.go
  internal/controllers/vgmanager/exec/exec.go
  internal/controllers/vgmanager/exec/test/mock_exec.go
  internal/controllers/vgmanager/wipe_devices.go
  internal/controllers/vgmanager/wipefs/wipefs.go
  internal/controllers/vgmanager/wipefs/wipefs_test.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/severity-low, jira/valid-bug

#688 OCPBUGS-37844: fix: resource sync fail -> progressing
  internal/controllers/lvmcluster/controller.go
  internal/controllers/lvmcluster/status.go
  internal/controllers/lvmcluster/status_test.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#690 OCPEDGE-1168: change DevicePath field to its own type
  CONTRIBUTING.md
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  cmd/vgmanager/vgmanager.go
  docs/design/lvm-operator-manager.md
  hack/debug.Dockerfile
  internal/controllers/symlink-resolver/resolver.go
  internal/controllers/symlink-resolver/resolver_test.go
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/devices.go
  internal/controllers/vgmanager/devices_test.go
  internal/controllers/vgmanager/filter/filter.go
  internal/controllers/vgmanager/filter/filter_test.go
  internal/controllers/vgmanager/kname_test.go
  internal/controllers/vgmanager/wipe_devices.go
  internal/controllers/vgmanager/wipe_devices_test.go
  test/performance/collector.go
  test/performance/parse.go
Labels: lgtm, approved, jira/valid-reference, size/XL

#695 OCPEDGE-1184: feat: enable multi-arch builds
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
Labels: approved, jira/valid-reference, size/XXL

#696 NO-JIRA: fix: correct the task name
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-push.yaml
Labels: approved, jira/valid-reference, size/XS

#692 OCPBUGS-35072: docs: graceful recovery documentation
  docs/troubleshooting.md
Labels: lgtm, approved, jira/valid-reference, size/L, jira/severity-moderate, jira/valid-bug
