Repository openshift/lvm-operator, pull requests merged in 2024-01, with the labels that each got.

#529 [release-4.14] OCPBUGS-25043: Fix CVE-2023-47108
  go.mod
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/severity-low, jira/valid-bug

#534 NO-JIRA: Must-Gather, Running gather scripts in background
  must-gather/collection-scripts/gather
Labels: lgtm, approved, jira/valid-reference, ok-to-test, size/S

#535 OCPBUGS-26502: Allow using symlinks for wiping a device
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/wipe_devices.go
  internal/controllers/vgmanager/wipe_devices_test.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, size/M, jira/valid-bug

#537 OCPBUGS-27095: Suggest workload partitioning annotation in the namespace
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#542 OCPBUGS-27330: fix: avoid topolvm-controller annotation generation increment
  internal/controllers/lvmcluster/resource/topolvm_controller.go
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/valid-bug

#543 OCPBUGS-27226: fix: add missing permissions to cluster scoped resources
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controllers/lvmcluster/controller.go
  internal/controllers/lvmcluster/resource/scc.go
  internal/controllers/lvmcluster/resource/topolvm_csi_driver.go
  internal/controllers/lvmcluster/resource/topolvm_snapshotclass.go
  internal/controllers/lvmcluster/resource/topolvm_storageclass.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-low, jira/valid-bug, size/S

#545 OCPBUGS-27327: Ensure LVMD config is created when volume group is present
  pkg/vgmanager/vgmanager_controller.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, size/M, jira/invalid-bug

#544 [release-4.14] OCPBUGS-27338: fix: avoid topolvm-controller annotation generation increment
  controllers/topolvm_controller.go
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/invalid-bug

#549 [release-4.15] OCPBUGS-27358: fix: add missing permissions to cluster scoped resources
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/topolvm_controller_role.yaml
  internal/controllers/lvmcluster/resource/scc.go
  internal/controllers/lvmcluster/resource/topolvm_csi_driver.go
  internal/controllers/lvmcluster/resource/topolvm_snapshotclass.go
  internal/controllers/lvmcluster/resource/topolvm_storageclass.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-low, jira/valid-bug, size/S

#550 OCPEDGE-811: chore: remove toolchain directive due to midstream incompatibility
  go.mod
Labels: lgtm, approved, jira/valid-reference, size/XS

#547 [release-4.13] OCPBUGS-27342: Suggest workload partitioning annotation in the namespace
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#528 [release-4.13] OCPBUGS-25042: Apply workload annotations to pod specs
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_custom_env.yaml.in
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
  controllers/topolvm_controller.go
  controllers/topolvm_node.go
  controllers/vgmanager.go
  controllers/vgmanager_daemonset.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-low, jira/valid-bug

#553 NO-JIRA: chore: decrease general log verbosity
  .pre-commit-config.yaml
  internal/controllers/lvmcluster/controller.go
  internal/controllers/lvmcluster/resource/lvm_volumegroup.go
  internal/controllers/lvmcluster/resource/scc.go
  internal/controllers/lvmcluster/resource/topolvm_csi_driver.go
  internal/controllers/lvmcluster/resource/topolvm_snapshotclass.go
  internal/controllers/lvmcluster/resource/topolvm_storageclass.go
  internal/controllers/lvmcluster/resource/vgmanager.go
  internal/controllers/node/removal/controller.go
  internal/controllers/vgmanager/controller.go
  internal/csi/registrar.go
Labels: lgtm, approved, jira/valid-reference, size/M

#551 [release-4.14] OCPBUGS-27403: fix: add missing permissions to cluster scoped resources
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/topolvm_controller_role.yaml
  controllers/scc.go
  controllers/topolvm_csi_driver.go
  controllers/topolvm_snapshotclass.go
  controllers/topolvm_storageclass.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-low, jira/invalid-bug

#552 [release-4.13] OCPBUGS-27404: fix: add missing permissions to cluster scoped resources
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/topolvm_controller_role.yaml
  controllers/scc.go
  controllers/topolvm_csi_driver.go
  controllers/topolvm_snapshotclass.go
  controllers/topolvm_storageclass.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-low, jira/invalid-bug

#548 [release-4.13] OCPBUGS-27357: fix: avoid topolvm-controller annotation generation increment
  controllers/topolvm_controller.go
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/valid-bug

#554 NO-JIRA: fix: do not set resource version in lvmcluster test
  api/v1alpha1/lvmcluster_test.go
Labels: lgtm, approved, jira/valid-reference, size/XS

#555 NO-ISSUE: chore: various small dependency bumps
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/go-openapi/swag/BENCHMARK.md
  vendor/github.com/go-openapi/swag/initialism_index.go
  vendor/github.com/go-openapi/swag/name_lexem.go
  vendor/github.com/go-openapi/swag/split.go
  vendor/github.com/go-openapi/swag/string_bytes.go
  vendor/github.com/go-openapi/swag/util.go
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/version7.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/be_comparable_to_matcher.go
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/version.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/handler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/netconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/version.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/attribute_group.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/doc.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/event.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/exception.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/http.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/resource.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/schema.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/trace.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_nonunix.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_others.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_windows.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, size/XXL

#556 OCPBUGS-26768: Revert back to file-based lvmd config to support different configs for each node
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  cmd/vgmanager/vgmanager.go
  config/rbac/vg_manager_role.yaml
  internal/controllers/constants/constants.go
  internal/controllers/lvmcluster/resource/topolvm_node.go
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvmd/lvmd.go
  internal/controllers/vgmanager/lvmd/mocks/mock_configurator.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, size/L, jira/invalid-bug

#557 OCPEDGE-821: chore: disable leader election for single replica deployment
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/default/manager_metrics_patch.yaml
  config/manager/manager.yaml
Labels: lgtm, approved, jira/valid-reference, size/S

#558 NO-JIRA: chore: reduce terminationGracePeriod to 10s on deploy
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, approved, jira/valid-reference, size/XS

#562 NO-JIRA: docs: relay to product docs
  README.md
Labels: lgtm, approved, jira/valid-reference, size/XS

#563 OCPEDGE-815: fix: pending shutdown on topology queue
  internal/csi/provisioner.go
Labels: lgtm, approved, jira/valid-reference, size/XS
