Repository openshift/lvm-operator, pull requests merged in 2024-02, with the labels that each got.

#566 OCPBUGS-27956: Revert back to file-based lvmd config to support different configs for each node
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  cmd/vgmanager/vgmanager.go
  config/rbac/vg_manager_role.yaml
  internal/controllers/constants/constants.go
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvmd/lvmd.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, size/L, jira/valid-bug

#568 [release-4.15] OCPBUGS-28966: fix: more sophisticated tagging migration
  catalog/lvms-operator/operator.yaml
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvm/lvm_test.go
  internal/controllers/vgmanager/lvm/mocks/mock_lvm.go
  internal/controllers/vgmanager/status.go
  internal/tagging/tagging.go
  internal/tagging/tagging_test.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/severity-moderate, jira/invalid-bug

#569 OCPBUGS-28975: fix: more sophisticated tagging migration
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvm/lvm_test.go
  internal/controllers/vgmanager/lvm/mocks/mock_lvm.go
  internal/migration/tagging/tagging.go
  internal/migration/tagging/tagging_test.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, size/L, jira/valid-bug

#570 OCPBUGS-29065: Reconcile topolvm node volumes
  internal/controllers/lvmcluster/resource/topolvm_node.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, size/XS, jira/invalid-bug

#571 OCPBUGS-29188: fix: resolve PV name via Symlink before comparing to KName
  .pre-commit-config.yaml
  internal/controllers/vgmanager/devices.go
  internal/controllers/vgmanager/filter/filter.go
  internal/controllers/vgmanager/filter/filter_test.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-low, jira/valid-bug, size/S

#573 [release-4.15] OCPBUGS-29351: fix: resolve PV name before comparing to KName
  internal/controllers/vgmanager/devices.go
  internal/controllers/vgmanager/filter/filter.go
  internal/controllers/vgmanager/filter/filter_test.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-low, jira/valid-bug, size/S

#574 OCPEDGE-781: chore: remove managed fields from all objs
  cmd/operator/operator.go
Labels: lgtm, approved, jira/valid-reference, size/S

#578 OCPBUGS-29699: fix: remove resource limits
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/constants.go
  controllers/topolvm_controller.go
  controllers/topolvm_node.go
  controllers/vgmanager_daemonset.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/invalid-bug

#579 OCPEDGE-526: Add missing LV-level encryption support to the limitations
  README.md
  internal/controllers/vgmanager/lvm/lvm_test.go
Labels: lgtm, approved, jira/valid-reference, size/M
