Repository openshift/lvm-operator, pull requests merged in 2024-09, with the labels that each got.

#701 OCPBUGS-13236: fix: allow deploy on cluster without prometheus
  Makefile
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manifests/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/webhook/kustomization.yaml
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#702 OCPBUGS-38929: fix: allow deploying thin pools with up to 100% of size percent
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#703 [release-4.17] OCPBUGS-39515: fix: allow deploying thin pools with up to 100% of size percent
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#709 OCPEDGE-1249: fix: introduce vgmanager file lock on start
  cmd/vgmanager/vgmanager.go
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
  internal/controllers/vgmanager/util/startlock.go
Labels: lgtm, approved, jira/valid-reference, size/L

#708 OCPEDGE-1247: make thin pool config editable
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_webhook.go
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/lvmd/lvmd.go
Labels: lgtm, approved, jira/valid-reference, size/M

#712 OCPBUGS-41632: fix: ensure uniq available devices
  internal/controllers/vgmanager/devices.go
  internal/controllers/vgmanager/devices_test.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/valid-bug

#715 OCPBUGS-41582: Remove topolvm-controller and topolvm-node pod references from docs
  README.md
  docs/design/architecture.md
  docs/design/lvm-operator-manager.md
  docs/troubleshooting.md
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#719 [release-4.15]NO-JIRA: feat(controller): disable http2
  cmd/operator/operator.go
  cmd/vgmanager/vgmanager.go
Labels: lgtm, approved, jira/valid-reference, size/S

#704 [release-4.16] OCPBUGS-39517: fix: allow deploying thin pools with up to 100% of size percent
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#705 [release-4.15] OCPBUGS-39527: fix: allow deploying thin pools with up to 100% of size percent
  api/v1alpha1/lvmcluster_test.go
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#706 [release-4.14] OCPBUGS-39530: fix: allow deploying thin pools with up to 100% of size percent
  api/v1alpha1/lvmcluster_types.go
  api/v1alpha1/lvmcluster_webhook.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
Labels: lgtm, approved, jira/valid-reference, size/L, jira/severity-moderate, jira/valid-bug

#720 OCPEDGE-1245: feat(tests) add lvmd.yaml test
  internal/controllers/vgmanager/controller_test.go
Labels: lgtm, approved, jira/valid-reference, size/M

#730 OCPBUGS-42385: fix: make sure that wipes are recorded by node
  internal/controllers/constants/constants.go
  internal/controllers/vgmanager/wipe_devices.go
  internal/controllers/vgmanager/wipe_devices_test.go
Labels: lgtm, approved, jira/valid-reference, jira/valid-bug, size/S
