Repository openshift/lvm-operator, pull requests merged in 2024-11, with the labels that each got.

#779 OCPBUGS-44377: Add migration logic for wipe refactor
  cmd/operator/operator.go
  internal/migration/wipe-refactor/annotate.go
  internal/migration/wipe-refactor/annotate_test.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/valid-bug

#782 OCPBUGS-43910: A non-resolvable device path causes all the devices to be excluded
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/devices_test.go
  internal/controllers/vgmanager/filter/filter.go
  internal/controllers/vgmanager/filter/filter_test.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/valid-bug

#788 NO-JIRA: Upgrade k8s.io/apimachinery to v0.29.10
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, size/XS

#790 OCPBUGS-44660: feat(Dockerfile): create /run/lock
  Dockerfile
  internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
Labels: lgtm, approved, jira/valid-reference, size/XS, jira/valid-bug

#789 OCPEDGE-1185: feat: adding a catalog template and generated files
  .codecov.yml
  .pre-commit-config.yaml
  .snyk
  Makefile
  PROJECT
  README.md
  catalog-template.yaml
  konflux-catalog.Dockerfile
  konflux-catalog/lvm-operator-catalog.yaml
Labels: lgtm, jira/valid-reference, size/XXL

#795 OCPEDGE-1299: feat: switching the operator to use fips enabled building
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  konflux.Dockerfile
Labels: lgtm, approved, jira/valid-reference, size/M
