Repository openshift/lvm-operator, pull requests merged in 2025-02, with the labels that each got.

#838 OCPEDGE-823: Add integration tests for Konflux
  .tekton/lvm-operator-integration-tests.yaml
  Makefile
  internal/controllers/vgmanager/exec/exec_test.go
  internal/controllers/vgmanager/lsblk/lsblk_test.go
Labels: lgtm, approved, jira/valid-reference, size/M

#849 NO-JIRA: Fix typo in lvmvolumegroupnodestatus during lvm must-gather collection
  must-gather/collection-scripts/gather_namespaced_resources
Labels: lgtm, approved, jira/valid-reference, size/XS

#851 NO-JIRA: Add missing bundle labels
  release/bundle/bundle.konflux.Dockerfile
Labels: approved, jira/valid-reference, size/XS

#852 feat: enable build-source-image in Konflux pipelines
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
Labels: approved, size/XS

#791 OCPEDGE-1593: feat(controller): skip controller name validation
  internal/controllers/lvmcluster/controller_watches.go
  internal/controllers/node/removal/controller.go
  internal/controllers/persistent-volume-claim/controller.go
  internal/controllers/persistent-volume/controller.go
  internal/controllers/vgmanager/controller.go
Labels: lgtm, approved, jira/valid-reference, size/S

#855 feat: separate single and multiarch Konflux pipelines
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
  release/must-gather/must-gather.konflux.Dockerfile
  release/operator/konflux.Dockerfile
Labels: approved, size/XXL

#856 OCPBUGS-49879: feat(topolvm): update openshift/topolvm
  go.mod
  go.sum
  vendor/github.com/topolvm/topolvm/.golangci.yml
  vendor/github.com/topolvm/topolvm/Makefile
  vendor/github.com/topolvm/topolvm/README.md
  vendor/github.com/topolvm/topolvm/cmd/lvmd/app/health.go
  vendor/github.com/topolvm/topolvm/cmd/lvmd/app/root.go
  vendor/github.com/topolvm/topolvm/internal/controller/node_controller.go
  vendor/github.com/topolvm/topolvm/internal/driver/controller.go
  vendor/github.com/topolvm/topolvm/internal/driver/internal/k8s/logicalvolume_service.go
  vendor/github.com/topolvm/topolvm/internal/driver/node.go
  vendor/github.com/topolvm/topolvm/internal/filesystem/util.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/command/lvm.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/command/lvm_command.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/command/lvm_error.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/command/lvm_lvs.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/command/lvm_vgs.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/lvservice.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/util.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/vgservice.go
  vendor/github.com/topolvm/topolvm/internal/runners/grpc.go
  vendor/github.com/topolvm/topolvm/internal/runners/metrics_exporter.go
  vendor/github.com/topolvm/topolvm/pkg/controller/logicalvolume_controller.go
  vendor/github.com/topolvm/topolvm/pkg/lvmd/embed.go
  vendor/github.com/topolvm/topolvm/versions.mk
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, jira/severity-critical, size/L, jira/invalid-bug

#857 OCPBUGS-49931: feat(topolvm): update openshift/topolvm
  go.mod
  go.sum
  vendor/github.com/topolvm/topolvm/internal/lvmd/lvservice.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/util.go
  vendor/github.com/topolvm/topolvm/internal/lvmd/vgservice.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, jira/severity-critical, size/M, jira/invalid-bug

#861 NO-JIRA: Add build pipeline files as trigger to jobs
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
Labels: approved, jira/valid-reference, size/S

#880 OCPEDGE-1620: make thin pool fields optional
  Makefile
  api/v1alpha1/lvmcluster_types.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
  internal/controllers/vgmanager/dmsetup/mocks/mock_dmsetup.go
  internal/controllers/vgmanager/lsblk/mocks/mock_lsblk.go
  internal/controllers/vgmanager/lvm/mocks/mock_lvm.go
  internal/controllers/vgmanager/lvmd/mocks/mock_configurator.go
  internal/controllers/vgmanager/wipefs/mocks/mock_wipefs.go
Labels: lgtm, approved, jira/valid-reference, size/S

#881 [release-4.18] OCPBUGS-52150: make thin pool fields optional
  api/v1alpha1/lvmcluster_types.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
  config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, jira/invalid-bug, size/S

#884 OCPEDGE-1588: feat: enterprise contract warnings updates
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
Labels: lgtm, approved, jira/valid-reference, size/L

#886 OCPEDGE-1588: fix: more updated task manifests
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
Labels: lgtm, approved, jira/valid-reference, size/XS
