Repository openshift/lvm-operator, pull requests merged in 2025-09, with the labels that each got.

#1267 [release-4.18] NO-JIRA: chore: konflux task updates
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
Labels: approved, jira/valid-reference, size/S

#1270 [release-4.14] NOJIRA: chore: tekton task updates
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
Labels: approved, size/S

#1289 NO-JIRA: chore: bumping the must-gather image sha
  release/bundle/bundle.konflux.Dockerfile
Labels: approved, jira/valid-reference, size/XS

#1292 [release-4.17] NO-JIRA: chore: bumping the operator image sha
  release/bundle/bundle.konflux.Dockerfile
Labels: approved, jira/valid-reference, size/XS

#1293 [release-4.16] NO-JIRA: chore: bumping the must-gather image sha
  release/bundle/bundle.konflux.Dockerfile
Labels: approved, jira/valid-reference, size/XS

#1296 [release-4.18] NO-JIRA: chore: tekton task updates to trigger new builds
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
Labels: approved, jira/valid-reference, size/S

#1298 [release-4.17] NO-JIRA: Release 4.17 tekton
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
Labels: approved, jira/valid-reference, size/S

#1334 KONFLUX-6210: chore: fix and set name and cpe label for lvm-operator-4-19
  release/operator/konflux.Dockerfile
Labels: lgtm, approved, jira/valid-reference, size/XS

#1337 chore(KONFLUX-6210): fix and set name and cpe label for lvm-operator-bundle-4-19
  release/bundle/bundle.konflux.Dockerfile
Labels: size/XS

#1338 NO-JIRA: fix: updated the scripting for setting up a test cluster
  Makefile
  README.md
  hack/configure_cluster_for_testing.sh
  hack/update_cluster_pull_secret.sh
Labels: approved, jira/valid-reference, size/L

#1352 NO-JIRA: fix: adding in rpm-lockfile management
  renovate.json
Labels: approved, jira/valid-reference, size/S

#1401 NO-JIRA: fix: removing precommit updates with renovate
  renovate.json
Labels: approved, jira/valid-reference, size/XS

#1402 [release-4.19] NO-JIRA: fix: dropping the precommit updates from renovate
  renovate.json
Labels: approved, jira/valid-reference, size/XS

#1403 [release-4.18] NO-JIRA: fix: dropping precommit updates from renovate
  renovate.json
Labels: approved, jira/valid-reference, size/XS
