Repository openshift/lvm-operator, pull requests merged in 2025-07, with the labels that each got.

#1052 NO-JIRA: bugfix stale node removals
  internal/controllers/lvmcluster/controller.go
Labels: lgtm, approved, jira/valid-reference, size/XS

#1075 [release-4.16] NO-JIRA: Release 4.16 konflux fix
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
Labels: approved, jira/valid-reference, size/S

#1071 NO-JIRA: fix: konflux pipeline target file update
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
Labels: approved, jira/valid-reference, size/S

#1076 [release-4.15] NO-JIRA: Release 4.15 konflux fix
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
Labels: approved, jira/valid-reference, size/S

#1090 NO-JIRA: fix: updating the rpmlock files
  release/must-gather/rpms.lock.yaml
  release/operator/rpms.lock.yaml
Labels: approved, jira/valid-reference, size/XL

#1096 [release-4.16] NO-JIRA: chore: updated rpm lockfile
  release/must-gather/rpms.lock.yaml
Labels: approved, jira/valid-reference, size/M

#1095 [release-4.17] NO-JIRA: Release 4.17 rpm lockfile updates
  release/must-gather/rpms.lock.yaml
  release/operator/rpms.lock.yaml
Labels: approved, jira/valid-reference, size/XL

#1105 NO-JIRA: fix: updating the application name for the tekton pipelines
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
Labels: approved, jira/valid-reference, size/S

#1099 [release-4.14] NO-JIRA: fix: updating the application name for the tekton pipelines
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
Labels: approved, jira/valid-reference, size/S

#1101 [release-4.16] NO-JIRA: fix: updating the application name for the tekton pipelines
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
Labels: approved, jira/valid-reference, size/S

#1100 [release-4.15] NO-JIRA: fix: updating the application name for the tekton pipelines
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
Labels: approved, jira/valid-reference, size/S

#955 OCPEDGE-1784: change default namespace
  CONTRIBUTING.md
  Makefile
  README.md
  api/v1alpha1/lvmcluster_test.go
  bundle/manifests/lvms-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
  config/olm-deploy/kustomization.yaml
  config/olm-deploy/lvms-catalogsource.yaml
  config/olm-deploy/lvms-operator-subscription.yaml
  config/olm-deploy/openshift-lvm-storage-namespace.yaml
  config/olm-deploy/openshift-lvm-storage-operatorgroup.yaml
  config/olm-deploy/openshift-storage-operatorgroup.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/webhook/kustomization.yaml
  docs/design/proposals/logical-volume-manager-storage-api-v2.md
  docs/troubleshooting.md
  hack/create-buildconfig.sh
  internal/controllers/lvmcluster/suite_test.go
  internal/controllers/persistent-volume-claim/controller_test.go
  internal/controllers/persistent-volume/controller_test.go
  internal/controllers/vgmanager/controller_test.go
  internal/migration/microlvms/cleanup_test.go
  internal/migration/wipe-refactor/annotate_test.go
  must-gather/collection-scripts/gather_namespaced_resources
  test/e2e/config_test.go
  test/e2e/subscription_test.go
  test/performance/collector_test.go
  test/performance/main.go
Labels: lgtm, approved, jira/valid-reference, size/L

#1124 NO-JIRA: Various Catalog updates
  .tekton/lvm-operator-catalog-v4.12-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.12-push.yaml
  .tekton/lvm-operator-catalog-v4.13-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.13-push.yaml
  .tekton/lvm-operator-catalog-v4.14-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.14-push.yaml
  .tekton/lvm-operator-catalog-v4.15-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.15-push.yaml
  .tekton/lvm-operator-catalog-v4.16-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.16-push.yaml
  .tekton/lvm-operator-catalog-v4.17-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.17-push.yaml
  .tekton/lvm-operator-catalog-v4.18-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.18-push.yaml
  .tekton/lvm-operator-catalog-v4.19-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.19-push.yaml
  catalogs/lvm-operator-catalog-v4.12.json
  catalogs/lvm-operator-catalog-v4.13.json
  catalogs/lvm-operator-catalog-v4.14.json
  catalogs/lvm-operator-catalog-v4.15.json
  catalogs/lvm-operator-catalog-v4.16.json
  catalogs/lvm-operator-catalog-v4.17.json
  catalogs/lvm-operator-catalog-v4.18.json
  catalogs/lvm-operator-catalog-v4.19.json
  hack/generate_catalogs.sh
  hack/generate_released_templates.sh
  templates/lvm-operator-catalog-v4.12-template.yaml
  templates/lvm-operator-catalog-v4.13-template.yaml
  templates/lvm-operator-catalog-v4.19-template.yaml
Labels: jira/valid-reference, size/XXL

#1098 OCPEDGE-1687: fix: added the must-gather annotation to the bundle
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
  release/hack/render_templates.sh
Labels: approved, jira/valid-reference, size/S

#1136 OCPEDGE-1937: feat(readme): add loop devices info
  README.md
Labels: lgtm, approved, jira/valid-reference, size/M

#1144 [release-4.17] NO-JIRA: Release 4.17 tekton triggers
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
Labels: approved, jira/valid-reference, size/S

#1143 [release-4.16] NO-JIRA: Release 4.16 tekton triggers
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
Labels: approved, jira/valid-reference, size/S

#1142 [release-4.15] NO-JIRA: Release 4.15 tekton triggers
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
Labels: approved, jira/valid-reference, size/S

#1140 NO-JIRA: chore: update the version to 4.19.1
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
  release/bundle/bundle.konflux.Dockerfile
  release/container-build.args
Labels: approved, jira/valid-reference, size/S

#1147 OCPEDGE-1980: feat(config): add network policies
  Makefile
  bundle.Dockerfile
  bundle/manifests/lvms-operator-network-policy_networking.k8s.io_v1_networkpolicy.yaml
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  bundle/manifests/vg-manager-network-policy_networking.k8s.io_v1_networkpolicy.yaml
  bundle/metadata/annotations.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/default/kustomization.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
  config/networkpolicy/kustomization.yaml
  config/networkpolicy/lvm-operator-networkpolicy.yaml
  config/networkpolicy/vgmanager-networkpolicy.yaml
Labels: lgtm, approved, jira/valid-reference, size/L

#1151 NO-JIRA: Release 4.19 trigger test
  .tekton/images-mirror-set.yaml
  release/must-gather/must-gather.konflux.Dockerfile
  release/operator/konflux.Dockerfile
Labels: approved, jira/valid-reference, size/S

#1159 OCPBUGS-43060: Improve deviceClasses.fsType description
  api/v1alpha1/lvmcluster_types.go
  bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
Labels: approved, jira/valid-reference, jira/valid-bug, size/S

#1149 NO-JIRA: Catalog pre release content
  .tekton/images-mirror-set.yaml
  .tekton/lvm-operator-catalog-v4.20-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.20-push.yaml
  Makefile
  README.md
  catalogs/lvm-operator-catalog-v4.14.json
  catalogs/lvm-operator-catalog-v4.15.json
  catalogs/lvm-operator-catalog-v4.16.json
  catalogs/lvm-operator-catalog-v4.17.json
  catalogs/lvm-operator-catalog-v4.18.json
  catalogs/lvm-operator-catalog-v4.19.json
  catalogs/lvm-operator-catalog-v4.20.json
  hack/generate_released_templates.sh
  hack/generate_templates.sh
  templates/lvm-operator-catalog-v4.14-template.yaml
  templates/lvm-operator-catalog-v4.15-template.yaml
  templates/lvm-operator-catalog-v4.16-template.yaml
  templates/lvm-operator-catalog-v4.17-template.yaml
  templates/lvm-operator-catalog-v4.18-template.yaml
  templates/lvm-operator-catalog-v4.19-template.yaml
  templates/lvm-operator-catalog-v4.20-template.yaml
Labels: jira/valid-reference, size/XXL

#1150 OCPBUGS-56352: feat(resource): deploy ServiceMonitor as resource
  bundle/manifests/lvms-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  catalog/lvms-operator/v0.0.1.yaml
  cmd/main.go
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controllers/lvmcluster/controller.go
  internal/controllers/lvmcluster/resource/servicemonitor.go
  internal/controllers/lvmcluster/suite_test.go
  test/e2e/config_test.go
Labels: lgtm, approved, jira/valid-reference, size/L, jira/valid-bug

#1162 Release management testing
  Makefile
  README.md
  hack/configure_cluster_for_testing.sh
  hack/generate_imagedigestmirrors.sh
  hack/generate_operator_install_manifests.sh
  hack/update_cluster_pull_secret.sh
Labels: approved, size/L
