Repository openshift/lvm-operator, pull requests merged in 2025-06, with the labels that each got.

#973 OCPEDGE-1925: 4.19 catalog
  .tekton/lvm-operator-catalog-v4.19-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.19-push.yaml
  catalogs/lvm-operator-catalog-v4.19.json
  templates/lvm-operator-catalog-v4.19-template.yaml
Labels: jira/valid-reference, size/XL

#975 OCPEDGE-1925: Catalog workflow
  .gitignore
  Makefile
  README.md
  hack/generate_catalogsource.sh
  hack/generate_imagedigestmirrors.sh
  hack/generate_operator_install_manifests.sh
  hack/update_cluster_pull_secret.sh
Labels: size/L

#980 OCPEDGE-1587: 4.19 konflux ec
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
  .tekton/multi-arch-build-pipeline.yaml
  release/must-gather/rpms.lock.yaml
  release/operator/rpms.lock.yaml
Labels: do-not-merge/hold, approved, jira/valid-reference, size/XXL

#1001 NO-JIRA: chore: merging in konflux pipelines to the release-4.19 branch
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
  release/bundle/bundle.konflux.Dockerfile
  release/must-gather/rpms.lock.yaml
  release/operator/rpms.lock.yaml
Labels: approved, jira/valid-reference, size/XXL

#1017 OCPEDGE-1921: feat(test): update e2e aws client creation
  test/e2e/aws_disk_test.go
  test/e2e/disk_setup_test.go
Labels: lgtm, approved, jira/valid-reference, size/S

#1000 OCPEDGE-1923: feat(config): allow custom namespace installation
  Makefile
  config/default/kustomization.yaml
  config/default/namespace.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/service.yaml
  config/webhook/validating_webhook_config.yaml
Labels: lgtm, approved, jira/valid-reference, size/L

#1040 [release-4.18] OCPEDGE-1838: Backport konflux config to release-4.18
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-integration-tests.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
  Makefile
  internal/controllers/vgmanager/exec/exec_test.go
  internal/controllers/vgmanager/lsblk/lsblk_test.go
  must-gather/konflux.Dockerfile
  release/bundle/artifacts.lock.yaml
  release/bundle/bundle.konflux.Dockerfile
  release/container-build.args
  release/hack/generate-release-helpers.sh
  release/hack/generate-release.sh
  release/hack/generate-rpm-lock.md
  release/hack/generate-rpm-lock.sh
  release/hack/render_templates.sh
  release/hack/update-konflux-task-refs.sh
  release/konflux.make
  release/must-gather/must-gather.konflux.Dockerfile
  release/must-gather/rpms.in.yaml
  release/must-gather/rpms.lock.yaml
  release/operator/konflux.Dockerfile
  release/operator/rpms.in.yaml
  release/operator/rpms.lock.yaml
Labels: approved, jira/valid-reference, size/XXL

#1047 [release-4.17] OCPEDGE-1941: OCPEDGE-1942: Konflux onboarding
  .pre-commit-config.yaml
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-integration-tests.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
  Makefile
  internal/cluster/sno.go
  internal/controllers/vgmanager/exec/exec_test.go
  internal/controllers/vgmanager/lsblk/lsblk_test.go
  release/bundle/artifacts.lock.yaml
  release/bundle/bundle.konflux.Dockerfile
  release/container-build.args
  release/hack/generate-release-helpers.sh
  release/hack/generate-release.sh
  release/hack/generate-rpm-lock.md
  release/hack/generate-rpm-lock.sh
  release/hack/render_templates.sh
  release/hack/update-konflux-task-refs.sh
  release/konflux.make
  release/must-gather/must-gather.konflux.Dockerfile
  release/must-gather/rpms.in.yaml
  release/must-gather/rpms.lock.yaml
  release/operator/konflux.Dockerfile
  release/operator/rpms.in.yaml
  release/operator/rpms.lock.yaml
  renovate.json
Labels: approved, jira/valid-reference, size/XXL

#1051 NO-JIRA: bugfix stale node removals
  internal/controllers/lvmcluster/controller.go
Labels: lgtm, approved, jira/valid-reference, size/XS

#1054 [release-4.16] OCPEDGE-1948: fix: konflux onboarding for 4.16
  .pre-commit-config.yaml
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-integration-tests.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
  Makefile
  internal/cluster/sno.go
  internal/controllers/vgmanager/exec/exec_test.go
  internal/controllers/vgmanager/lsblk/lsblk_test.go
  release/bundle/artifacts.lock.yaml
  release/bundle/bundle.konflux.Dockerfile
  release/container-build.args
  release/hack/generate-release-helpers.sh
  release/hack/generate-release.sh
  release/hack/generate-rpm-lock.md
  release/hack/generate-rpm-lock.sh
  release/hack/render_templates.sh
  release/hack/update-konflux-task-refs.sh
  release/konflux.make
  release/must-gather/must-gather.konflux.Dockerfile
  release/must-gather/rpms.in.yaml
  release/must-gather/rpms.lock.yaml
  release/operator/konflux.Dockerfile
  release/operator/rpms.in.yaml
  release/operator/rpms.lock.yaml
  renovate.json
Labels: approved, jira/valid-reference, size/XXL

#1055 [release-4.16] NO-JIRA: Must-Gather konflux reference fix
  release/bundle/bundle.konflux.Dockerfile
Labels: approved, jira/valid-reference, size/XS
