Repository openshift/lvm-operator, pull requests merged in 2025-03, with the labels that each got.

#897 NO-JIRA: fix: adding in the required rpms signature scan task for the build pipelines
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
Labels: lgtm, approved, jira/valid-reference, size/M

#900 OCPEDGE-1648: feat: added our LICENSE file to the build container images
  Dockerfile
  release/must-gather/must-gather.konflux.Dockerfile
  release/operator/konflux.Dockerfile
Labels: lgtm, approved, jira/valid-reference, size/S

#902 NO-JIRA: chore: build pipeline updates, added a script for automation
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
  release/hack/update-konflux-task-refs.sh
  release/konflux.make
Labels: lgtm, approved, jira/valid-reference, size/L

#898 OCPBUGS-52351: Retry Nodes with not-ready taint
  internal/controllers/lvmcluster/controller.go
  internal/controllers/lvmcluster/resource/csi_node.go
  internal/controllers/lvmcluster/resource/lvm_volumegroupnodestatus.go
  internal/controllers/lvmcluster/selector/selector.go
  internal/controllers/lvmcluster/status.go
Labels: lgtm, approved, jira/valid-reference, jira/severity-important, size/M, jira/valid-bug

#906 NO-JIRA: chore: konflux task manifest updates
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
Labels: lgtm, approved, jira/valid-reference, size/S

#910 OCPEDGE-1650: fix: skip the ecosystem cert preflight check for the bundle image
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/single-arch-build-pipeline.yaml
Labels: lgtm, approved, jira/valid-reference, size/S

#911 OCPEDGE-1650: feat: moving the version tag info to build a build args file
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvm-operator-push.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
  .tekton/single-arch-build-pipeline.yaml
  release/bundle/bundle.konflux.Dockerfile
  release/container-build.args
  release/must-gather/must-gather.konflux.Dockerfile
  release/operator/konflux.Dockerfile
Labels: do-not-merge/hold, approved, jira/valid-reference, size/M

#914 OCPEDGE-1688: fix: setting the non-root user for the must-gather image
  must-gather/Dockerfile
  release/must-gather/must-gather.konflux.Dockerfile
Labels: lgtm, approved, jira/valid-reference, size/XS

#924 fix: bundle tagging
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-pull-request.yaml
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
Labels: approved, size/M

#931 OCPEDGE-1594: fix: adding back in the must-gather required binaries
  .tekton/lvms-must-gather-pull-request.yaml
  .tekton/lvms-must-gather-push.yaml
  release/hack/generate-rpm-lock.md
  release/hack/generate-rpm-lock.sh
  release/konflux.make
  release/must-gather/must-gather.konflux.Dockerfile
  release/must-gather/rpms.in.yaml
  release/must-gather/rpms.lock.yaml
Labels: lgtm, approved, jira/valid-reference, size/XXL
