Repository openshift/lvm-operator, pull requests merged in 2025-08, with the labels that each got.

#1170 NO-JIRA: fix: added the ability to specify the snapshot to test and added bund…
  .gitignore
  Makefile
  hack/configure_cluster_for_testing.sh
  hack/generate_operator_install_manifests.sh
Labels: approved, jira/valid-reference, size/M

#1175 OCPBUGS-51139: bump openshift/topolvm
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controllers/lvmcluster/controller.go
Labels: lgtm, approved, jira/valid-reference, jira/valid-bug, size/S

#1169 OCPBUGS-60280: [release-4.18] feat(resource): deploy ServiceMonitor as resource
  bundle/manifests/lvms-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  catalog/lvms-operator/v0.0.1.yaml
  cmd/main.go
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controllers/lvmcluster/controller.go
  internal/controllers/lvmcluster/resource/servicemonitor.go
  internal/controllers/lvmcluster/suite_test.go
  test/e2e/config_test.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/resource.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/alertmanager_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/podmonitor_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/probe_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/prometheus_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/prometheusrule_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/servicemonitor_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, size/XXL, jira/valid-bug

#1178 NO-JIRA: fix: dropped the candidate channel
  catalogs/lvm-operator-catalog-v4.14.json
  catalogs/lvm-operator-catalog-v4.15.json
  catalogs/lvm-operator-catalog-v4.16.json
  catalogs/lvm-operator-catalog-v4.17.json
  catalogs/lvm-operator-catalog-v4.18.json
  catalogs/lvm-operator-catalog-v4.19.json
  catalogs/lvm-operator-catalog-v4.20.json
  hack/generate_catalogs.sh
  hack/generate_templates.sh
  templates/lvm-operator-catalog-v4.14-template.yaml
  templates/lvm-operator-catalog-v4.15-template.yaml
  templates/lvm-operator-catalog-v4.16-template.yaml
  templates/lvm-operator-catalog-v4.17-template.yaml
  templates/lvm-operator-catalog-v4.18-template.yaml
  templates/lvm-operator-catalog-v4.19-template.yaml
  templates/lvm-operator-catalog-v4.20-template.yaml
Labels: jira/valid-reference, size/XXL

#1206 NO-JIRA: fix: updating the pipeline names to match konflux requirements
  .tekton/lvm-operator-catalog-v4.14-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.14-push.yaml
  .tekton/lvm-operator-catalog-v4.15-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.15-push.yaml
  .tekton/lvm-operator-catalog-v4.16-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.16-push.yaml
  .tekton/lvm-operator-catalog-v4.17-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.17-push.yaml
  .tekton/lvm-operator-catalog-v4.18-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.18-push.yaml
  .tekton/lvm-operator-catalog-v4.19-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.19-push.yaml
  .tekton/lvm-operator-catalog-v4.20-pull-request.yaml
  .tekton/lvm-operator-catalog-v4.20-push.yaml
Labels: jira/valid-reference, size/S

#1203 NO-JIRA: Revert network policies
  Makefile
  bundle.Dockerfile
  bundle/manifests/lvms-default-deny_networking.k8s.io_v1_networkpolicy.yaml
  bundle/manifests/lvms-operator-network-policy_networking.k8s.io_v1_networkpolicy.yaml
  bundle/manifests/lvms-operator.clusterserviceversion.yaml
  bundle/manifests/vg-manager-network-policy_networking.k8s.io_v1_networkpolicy.yaml
  bundle/metadata/annotations.yaml
  catalog/lvms-operator/v0.0.1.yaml
  config/default/kustomization.yaml
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/bases/lvms-operator.clusterserviceversion.yaml
  config/networkpolicy/default-deny-networkpolicy.yaml
  config/networkpolicy/kustomization.yaml
  config/networkpolicy/lvm-operator-networkpolicy.yaml
  config/networkpolicy/vgmanager-networkpolicy.yaml
Labels: lgtm, approved, jira/valid-reference, size/L

#1214 [release-4.19] NOJIRA: fix: dropping the prefetch input from the bundle
  .tekton/lvm-operator-bundle-pull-request.yaml
  .tekton/lvm-operator-bundle-push.yaml
  release/bundle/artifacts.lock.yaml
  renovate.json
Labels: approved, size/S

#1212 OCPBUGS-58385: feat(wiping): add y option to vgcreate
  internal/controllers/vgmanager/controller.go
  internal/controllers/vgmanager/controller_test.go
  internal/controllers/vgmanager/devices.go
  internal/controllers/vgmanager/lvm/lvm.go
  internal/controllers/vgmanager/lvm/lvm_test.go
  internal/controllers/vgmanager/lvm/mocks/mock_lvm.go
Labels: lgtm, approved, jira/valid-reference, size/M, jira/severity-moderate, jira/valid-bug

#1217 NO-JIRA: fix: updating after renovate broke the catalogs and pyxis changed our staging location
  catalogs/lvm-operator-catalog-v4.14.json
  catalogs/lvm-operator-catalog-v4.15.json
  catalogs/lvm-operator-catalog-v4.16.json
  catalogs/lvm-operator-catalog-v4.17.json
  catalogs/lvm-operator-catalog-v4.18.json
  catalogs/lvm-operator-catalog-v4.19.json
  catalogs/lvm-operator-catalog-v4.20.json
  hack/generate_catalogs.sh
  hack/generate_templates.sh
  renovate.json
  templates/lvm-operator-catalog-v4.14-template.yaml
  templates/lvm-operator-catalog-v4.15-template.yaml
  templates/lvm-operator-catalog-v4.16-template.yaml
  templates/lvm-operator-catalog-v4.17-template.yaml
  templates/lvm-operator-catalog-v4.18-template.yaml
  templates/lvm-operator-catalog-v4.19-template.yaml
  templates/lvm-operator-catalog-v4.20-template.yaml
Labels: jira/valid-reference, size/XXL

#1231 NOJIRA: Release 4.19.1 redo
  releases/lvm-operator-catalog-4-19-d7vgb.yaml
  releases/lvm-operator-rhba-v4.19.1.yaml
Labels: approved, size/XS, qe-approved

#1238 NO-JIRA: chore: 4.19 and 4.20 catalog updates
  catalogs/lvm-operator-catalog-v4.19.json
  catalogs/lvm-operator-catalog-v4.20.json
  hack/generate_templates.sh
  templates/lvm-operator-catalog-v4.19-template.yaml
  templates/lvm-operator-catalog-v4.20-template.yaml
Labels: jira/valid-reference, size/XL

#1242 NO-JIRA: fix: trying to fix nudging
  .tekton/images-mirror-set.yaml
  .tekton/multi-arch-build-pipeline.yaml
  .tekton/single-arch-build-pipeline.yaml
Labels: approved, jira/valid-reference, size/S
